(() => {
    if (window.LocalConnectI18n) return;

    const STORAGE_KEY = "localConnectLanguage";
    const languages = {
        en: { label: "English", locale: "en-IN" },
        kn: { label: "ಕನ್ನಡ", locale: "kn-IN" },
        te: { label: "తెలుగు", locale: "te-IN" },
        hi: { label: "हिन्दी", locale: "hi-IN" }
    };

    const translations = {
        kn: {
            "Home services": "ಮನೆ ಸೇವೆಗಳು", "Vehicle care": "ವಾಹನ ಸೇವೆ", "Beauty": "ಸೌಂದರ್ಯ",
            "Location": "ಸ್ಥಳ", "Use current location": "ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ", "Search services": "ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ",
            "Search for a service": "ಸೇವೆಯನ್ನು ಹುಡುಕಿ", "Search for ‘plumbing’": "‘ಪ್ಲಂಬಿಂಗ್’ ಹುಡುಕಿ", "Search": "ಹುಡುಕಿ",
            "Notifications": "ಅಧಿಸೂಚನೆಗಳು", "Sign In": "ಲಾಗಿನ್", "Sign in": "ಲಾಗಿನ್", "Log out": "ಲಾಗ್ ಔಟ್",
            "Verified professionals. Clear prices. Local expertise.": "ಪರಿಶೀಲಿತ ವೃತ್ತಿಪರರು. ಸ್ಪಷ್ಟ ಬೆಲೆಗಳು. ಸ್ಥಳೀಯ ಪರಿಣತಿ.",
            "Trusted local professionals, just a booking away.": "ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ವೃತ್ತಿಪರರು, ಒಂದು ಬುಕ್ಕಿಂಗ್ ದೂರದಲ್ಲಿ.",
            "Find verified professionals for cleaning, plumbing, electrical repairs and more — all in one place.": "ಸ್ವಚ್ಛತೆ, ಪ್ಲಂಬಿಂಗ್, ವಿದ್ಯುತ್ ದುರಸ್ತಿ ಮತ್ತು ಇನ್ನಷ್ಟು ಸೇವೆಗಳಿಗೆ ಪರಿಶೀಲಿತ ವೃತ್ತಿಪರರನ್ನು ಒಂದೇ ಸ್ಥಳದಲ್ಲಿ ಹುಡುಕಿ.",
            "Verified professionals": "ಪರಿಶೀಲಿತ ವೃತ್ತಿಪರರು", "Transparent pricing": "ಪಾರದರ್ಶಕ ಬೆಲೆ", "Secure booking": "ಸುರಕ್ಷಿತ ಬುಕ್ಕಿಂಗ್", "Local support": "ಸ್ಥಳೀಯ ಸಹಾಯ",
            "Plumbing": "ಪ್ಲಂಬಿಂಗ್", "Electrical": "ವಿದ್ಯುತ್", "Cleaning": "ಸ್ವಚ್ಛತೆ", "Vehicle Repair": "ವಾಹನ ದುರಸ್ತಿ",
            "Appliance Repair": "ಉಪಕರಣ ದುರಸ್ತಿ", "Beauty Services": "ಸೌಂದರ್ಯ ಸೇವೆಗಳು", "Moving Services": "ಸ್ಥಳಾಂತರ ಸೇವೆಗಳು", "Emergency Services": "ತುರ್ತು ಸೇವೆಗಳು",
            "More Services": "ಇನ್ನಷ್ಟು ಸೇವೆಗಳು", "Recommended professionals": "ಶಿಫಾರಸು ಮಾಡಿದ ವೃತ್ತಿಪರರು", "Top-rated experts near you": "ನಿಮ್ಮ ಹತ್ತಿರದ ಉನ್ನತ ರೇಟಿಂಗ್ ತಜ್ಞರು",
            "Explore services": "ಸೇವೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ", "Popular categories": "ಜನಪ್ರಿಯ ವರ್ಗಗಳು", "View all services": "ಎಲ್ಲ ಸೇವೆಗಳು",
            "Complete catalogue": "ಸಂಪೂರ್ಣ ಪಟ್ಟಿ", "All services": "ಎಲ್ಲ ಸೇವೆಗಳು", "Choose a category to see its services, prices and available professionals.": "ಸೇವೆಗಳು, ಬೆಲೆಗಳು ಮತ್ತು ಲಭ್ಯ ವೃತ್ತಿಪರರನ್ನು ನೋಡಲು ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
            "Service category": "ಸೇವಾ ವರ್ಗ", "Choose what you need": "ನಿಮಗೆ ಬೇಕಾದುದನ್ನು ಆಯ್ಕೆಮಾಡಿ", "Available services": "ಲಭ್ಯ ಸೇವೆಗಳು", "Available near you": "ನಿಮ್ಮ ಹತ್ತಿರ ಲಭ್ಯ",
            "Service professionals": "ಸೇವಾ ವೃತ್ತಿಪರರು", "View professionals and book this service": "ವೃತ್ತಿಪರರನ್ನು ನೋಡಿ ಮತ್ತು ಸೇವೆ ಬುಕ್ ಮಾಡಿ", "View details": "ವಿವರ ನೋಡಿ", "Book": "ಬುಕ್ ಮಾಡಿ",
            "About this professional": "ಈ ವೃತ್ತಿಪರರ ಬಗ್ಗೆ", "Services & prices": "ಸೇವೆಗಳು ಮತ್ತು ಬೆಲೆಗಳು", "Included with every booking": "ಪ್ರತಿ ಬುಕ್ಕಿಂಗ್‌ನಲ್ಲಿ ಒಳಗೊಂಡಿದೆ", "Reviews": "ವಿಮರ್ಶೆಗಳು",
            "Book this professional": "ಈ ವೃತ್ತಿಪರರನ್ನು ಬುಕ್ ಮಾಡಿ", "Starting from": "ಆರಂಭಿಕ ಬೆಲೆ", "Start your booking": "ಬುಕ್ಕಿಂಗ್ ಆರಂಭಿಸಿ", "Choose the service you need": "ನಿಮಗೆ ಬೇಕಾದ ಸೇವೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
            "Service": "ಸೇವೆ", "Schedule": "ಸಮಯ", "Address": "ವಿಳಾಸ", "Confirm": "ದೃಢೀಕರಿಸಿ", "Select one service": "ಒಂದು ಸೇವೆ ಆಯ್ಕೆಮಾಡಿ", "Continue": "ಮುಂದುವರಿಸಿ", "Back": "ಹಿಂದೆ",
            "When should the professional arrive?": "ವೃತ್ತಿಪರರು ಯಾವಾಗ ಬರಬೇಕು?", "Choose an available date and arrival window.": "ಲಭ್ಯ ದಿನಾಂಕ ಮತ್ತು ಸಮಯ ಆಯ್ಕೆಮಾಡಿ.", "Select a date": "ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ", "Select a time": "ಸಮಯ ಆಯ್ಕೆಮಾಡಿ",
            "Where do you need the service?": "ಸೇವೆ ಎಲ್ಲಿ ಬೇಕು?", "Full name": "ಪೂರ್ಣ ಹೆಸರು", "Phone number": "ದೂರವಾಣಿ ಸಂಖ್ಯೆ", "Address label": "ವಿಳಾಸದ ಹೆಸರು", "City": "ನಗರ", "State": "ರಾಜ್ಯ", "PIN code": "ಪಿನ್ ಕೋಡ್", "Landmark": "ಗುರುತು ಸ್ಥಳ",
            "Review and confirm": "ಪರಿಶೀಲಿಸಿ ದೃಢೀಕರಿಸಿ", "Payment method": "ಪಾವತಿ ವಿಧಾನ", "Pay after service": "ಸೇವೆಯ ನಂತರ ಪಾವತಿ", "Save booking request": "ಬುಕ್ಕಿಂಗ್ ವಿನಂತಿ ಉಳಿಸಿ", "Done": "ಮುಗಿದಿದೆ",
            "Trusted help, close to home": "ಮನೆಯ ಹತ್ತಿರ ವಿಶ್ವಾಸಾರ್ಹ ಸಹಾಯ", "Your bookings.\nYour trusted professionals.": "ನಿಮ್ಮ ಬುಕ್ಕಿಂಗ್‌ಗಳು.\nನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ವೃತ್ತಿಪರರು.", "Welcome back": "ಮತ್ತೆ ಸ್ವಾಗತ",
            "Email address": "ಇಮೇಲ್ ವಿಳಾಸ", "Password": "ಪಾಸ್‌ವರ್ಡ್", "Forgot password?": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?", "Enter your password": "ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ", "Show": "ತೋರಿಸಿ", "Hide": "ಮರೆಮಾಡಿ", "Remember me": "ನನ್ನನ್ನು ನೆನಪಿಡಿ",
            "Don’t have an account?": "ಖಾತೆ ಇಲ್ಲವೇ?", "Create account": "ಖಾತೆ ರಚಿಸಿ", "Join the community": "ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ", "Create your account": "ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ", "Already have an account?": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
            "Verification code": "ಪರಿಶೀಲನಾ ಕೋಡ್", "Send code": "ಕೋಡ್ ಕಳುಹಿಸಿ", "Resend code": "ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಿ", "Confirm password": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ", "Reset password": "ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ", "Update password": "ಪಾಸ್‌ವರ್ಡ್ ನವೀಕರಿಸಿ",
            "My account": "ನನ್ನ ಖಾತೆ", "Overview": "ಅವಲೋಕನ", "My profile": "ನನ್ನ ಪ್ರೊಫೈಲ್", "Saved addresses": "ಉಳಿಸಿದ ವಿಳಾಸಗಳು", "Active bookings": "ಸಕ್ರಿಯ ಬುಕ್ಕಿಂಗ್‌ಗಳು", "Booking history": "ಬುಕ್ಕಿಂಗ್ ಇತಿಹಾಸ", "Favourites": "ಮೆಚ್ಚಿನವು", "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            "Good": "ಶುಭ", "morning": "ಬೆಳಗ್ಗೆ", "afternoon": "ಮಧ್ಯಾಹ್ನ", "evening": "ಸಂಜೆ", "Customer": "ಗ್ರಾಹಕ", "Book a service": "ಸೇವೆ ಬುಕ್ ಮಾಡಿ", "Upcoming": "ಮುಂಬರುವ", "Completed services": "ಪೂರ್ಣಗೊಂಡ ಸೇವೆಗಳು", "Total spent": "ಒಟ್ಟು ವೆಚ್ಚ",
            "Latest booking": "ಇತ್ತೀಚಿನ ಬುಕ್ಕಿಂಗ್", "Quick actions": "ತ್ವರಿತ ಕಾರ್ಯಗಳು", "Edit profile": "ಪ್ರೊಫೈಲ್ ತಿದ್ದುಪಡಿ", "Add an address": "ವಿಳಾಸ ಸೇರಿಸಿ", "Find a professional": "ವೃತ್ತಿಪರರನ್ನು ಹುಡುಕಿ", "Account settings": "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
            "Profile photo": "ಪ್ರೊಫೈಲ್ ಚಿತ್ರ", "Date of birth": "ಹುಟ್ಟಿದ ದಿನಾಂಕ", "Preferred language": "ಆದ್ಯತೆಯ ಭಾಷೆ", "Discard changes": "ಬದಲಾವಣೆ ರದ್ದು", "Save profile": "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ", "Add address": "ವಿಳಾಸ ಸೇರಿಸಿ", "Save address": "ವಿಳಾಸ ಉಳಿಸಿ", "Cancel": "ರದ್ದು",
            "Past services": "ಹಿಂದಿನ ಸೇವೆಗಳು", "Search bookings": "ಬುಕ್ಕಿಂಗ್ ಹುಡುಕಿ", "All statuses": "ಎಲ್ಲ ಸ್ಥಿತಿಗಳು", "Completed": "ಪೂರ್ಣಗೊಂಡಿದೆ", "Cancelled": "ರದ್ದುಪಡಿಸಲಾಗಿದೆ", "Favourite professionals": "ಮೆಚ್ಚಿನ ವೃತ್ತಿಪರರು", "Mark all as read": "ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತಿಸಿ",
            "Preferences and security": "ಆದ್ಯತೆಗಳು ಮತ್ತು ಭದ್ರತೆ", "Booking updates": "ಬುಕ್ಕಿಂಗ್ ನವೀಕರಣಗಳು", "Offers and recommendations": "ಆಫರ್‌ಗಳು ಮತ್ತು ಶಿಫಾರಸುಗಳು", "Email receipts": "ಇಮೇಲ್ ರಸೀದಿಗಳು", "Appearance": "ಗೋಚರತೆ", "Theme": "ಥೀಮ್", "Light": "ಬೆಳಕು", "Night": "ರಾತ್ರಿ", "Save settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ"
        },
        te: {
            "Home services": "గృహ సేవలు", "Vehicle care": "వాహన సేవ", "Beauty": "అందం", "Location": "ప్రదేశం", "Use current location": "ప్రస్తుత ప్రదేశాన్ని ఉపయోగించండి", "Search services": "సేవలను వెతకండి", "Search for a service": "సేవ కోసం వెతకండి", "Search for ‘plumbing’": "‘ప్లంబింగ్’ కోసం వెతకండి", "Search": "వెతకండి", "Notifications": "నోటిఫికేషన్లు", "Sign In": "లాగిన్", "Sign in": "లాగిన్", "Log out": "లాగ్ అవుట్",
            "Verified professionals. Clear prices. Local expertise.": "ధృవీకరించిన నిపుణులు. స్పష్టమైన ధరలు. స్థానిక నైపుణ్యం.", "Trusted local professionals, just a booking away.": "నమ్మకమైన స్థానిక నిపుణులు, ఒక్క బుకింగ్ దూరంలో.", "Find verified professionals for cleaning, plumbing, electrical repairs and more — all in one place.": "క్లీనింగ్, ప్లంబింగ్, ఎలక్ట్రికల్ మరమ్మతులు మరియు మరిన్ని సేవలకు ధృవీకరించిన నిపుణులను ఒకేచోట కనుగొనండి.",
            "Verified professionals": "ధృవీకరించిన నిపుణులు", "Transparent pricing": "పారదర్శక ధరలు", "Secure booking": "సురక్షిత బుకింగ్", "Local support": "స్థానిక సహాయం", "Plumbing": "ప్లంబింగ్", "Electrical": "ఎలక్ట్రికల్", "Cleaning": "క్లీనింగ్", "Vehicle Repair": "వాహన మరమ్మతు", "Appliance Repair": "ఉపకరణ మరమ్మతు", "Beauty Services": "అందం సేవలు", "Moving Services": "మూవింగ్ సేవలు", "Emergency Services": "అత్యవసర సేవలు", "More Services": "మరిన్ని సేవలు",
            "Recommended professionals": "సిఫార్సు చేసిన నిపుణులు", "Top-rated experts near you": "మీ సమీపంలోని ఉత్తమ నిపుణులు", "Explore services": "సేవలను అన్వేషించండి", "Popular categories": "ప్రసిద్ధ విభాగాలు", "View all services": "అన్ని సేవలు", "Complete catalogue": "పూర్తి జాబితా", "All services": "అన్ని సేవలు", "Choose a category to see its services, prices and available professionals.": "సేవలు, ధరలు మరియు అందుబాటులో ఉన్న నిపుణులను చూడటానికి విభాగాన్ని ఎంచుకోండి.",
            "Service category": "సేవా విభాగం", "Choose what you need": "మీకు కావలసింది ఎంచుకోండి", "Available services": "అందుబాటులో ఉన్న సేవలు", "Available near you": "మీ సమీపంలో అందుబాటులో", "Service professionals": "సేవా నిపుణులు", "View professionals and book this service": "నిపుణులను చూసి సేవను బుక్ చేయండి", "View details": "వివరాలు", "Book": "బుక్ చేయండి", "About this professional": "ఈ నిపుణుడి గురించి", "Services & prices": "సేవలు మరియు ధరలు", "Included with every booking": "ప్రతి బుకింగ్‌లో ఉంటుంది", "Reviews": "సమీక్షలు", "Book this professional": "ఈ నిపుణుడిని బుక్ చేయండి", "Starting from": "ప్రారంభ ధర",
            "Start your booking": "బుకింగ్ ప్రారంభించండి", "Choose the service you need": "మీకు కావలసిన సేవను ఎంచుకోండి", "Service": "సేవ", "Schedule": "సమయం", "Address": "చిరునామా", "Confirm": "నిర్ధారించండి", "Select one service": "ఒక సేవను ఎంచుకోండి", "Continue": "కొనసాగించండి", "Back": "వెనుకకు", "When should the professional arrive?": "నిపుణుడు ఎప్పుడు రావాలి?", "Choose an available date and arrival window.": "అందుబాటులో ఉన్న తేదీ మరియు సమయాన్ని ఎంచుకోండి.", "Select a date": "తేదీ ఎంచుకోండి", "Select a time": "సమయం ఎంచుకోండి", "Where do you need the service?": "సేవ ఎక్కడ కావాలి?", "Full name": "పూర్తి పేరు", "Phone number": "ఫోన్ నంబర్", "Address label": "చిరునామా పేరు", "City": "నగరం", "State": "రాష్ట్రం", "PIN code": "పిన్ కోడ్", "Landmark": "ల్యాండ్‌మార్క్", "Review and confirm": "పరిశీలించి నిర్ధారించండి", "Payment method": "చెల్లింపు విధానం", "Pay after service": "సేవ తర్వాత చెల్లించండి", "Save booking request": "బుకింగ్ అభ్యర్థనను సేవ్ చేయండి", "Done": "పూర్తయింది",
            "Trusted help, close to home": "ఇంటి దగ్గర నమ్మకమైన సహాయం", "Welcome back": "తిరిగి స్వాగతం", "Email address": "ఇమెయిల్ చిరునామా", "Password": "పాస్‌వర్డ్", "Forgot password?": "పాస్‌వర్డ్ మర్చిపోయారా?", "Enter your password": "పాస్‌వర్డ్ నమోదు చేయండి", "Show": "చూపించు", "Hide": "దాచు", "Remember me": "నన్ను గుర్తుంచుకోండి", "Don’t have an account?": "ఖాతా లేదా?", "Create account": "ఖాతా సృష్టించండి", "Join the community": "కమ్యూనిటీలో చేరండి", "Create your account": "మీ ఖాతాను సృష్టించండి", "Already have an account?": "ఇప్పటికే ఖాతా ఉందా?", "Verification code": "ధృవీకరణ కోడ్", "Send code": "కోడ్ పంపండి", "Resend code": "కోడ్ మళ్లీ పంపండి", "Confirm password": "పాస్‌వర్డ్ నిర్ధారించండి", "Reset password": "పాస్‌వర్డ్ రీసెట్", "Update password": "పాస్‌వర్డ్ నవీకరించండి",
            "My account": "నా ఖాతా", "Overview": "అవలోకనం", "My profile": "నా ప్రొఫైల్", "Saved addresses": "సేవ్ చేసిన చిరునామాలు", "Active bookings": "యాక్టివ్ బుకింగ్‌లు", "Booking history": "బుకింగ్ చరిత్ర", "Favourites": "ఇష్టమైనవి", "Settings": "సెట్టింగ్‌లు", "Good": "శుభ", "morning": "ఉదయం", "afternoon": "మధ్యాహ్నం", "evening": "సాయంత్రం", "Customer": "కస్టమర్", "Book a service": "సేవను బుక్ చేయండి", "Upcoming": "రాబోయేవి", "Completed services": "పూర్తయిన సేవలు", "Total spent": "మొత్తం ఖర్చు", "Latest booking": "తాజా బుకింగ్", "Quick actions": "త్వరిత చర్యలు", "Edit profile": "ప్రొఫైల్ మార్చండి", "Add an address": "చిరునామా జోడించండి", "Find a professional": "నిపుణుడిని వెతకండి", "Account settings": "ఖాతా సెట్టింగ్‌లు", "Profile photo": "ప్రొఫైల్ ఫోటో", "Date of birth": "పుట్టిన తేదీ", "Preferred language": "ఇష్టమైన భాష", "Discard changes": "మార్పులు రద్దు", "Save profile": "ప్రొఫైల్ సేవ్", "Add address": "చిరునామా జోడించండి", "Save address": "చిరునామా సేవ్", "Cancel": "రద్దు", "Past services": "గత సేవలు", "Search bookings": "బుకింగ్‌లను వెతకండి", "All statuses": "అన్ని స్థితులు", "Completed": "పూర్తయింది", "Cancelled": "రద్దయింది", "Favourite professionals": "ఇష్టమైన నిపుణులు", "Mark all as read": "అన్నీ చదివినట్లు గుర్తించండి", "Preferences and security": "ప్రాధాన్యతలు మరియు భద్రత", "Booking updates": "బుకింగ్ అప్‌డేట్లు", "Offers and recommendations": "ఆఫర్లు మరియు సిఫార్సులు", "Email receipts": "ఇమెయిల్ రసీదులు", "Appearance": "రూపం", "Theme": "థీమ్", "Light": "లైట్", "Night": "నైట్", "Save settings": "సెట్టింగ్‌లు సేవ్"
        },
        hi: {
            "Home services": "घरेलू सेवाएँ", "Vehicle care": "वाहन सेवा", "Beauty": "सौंदर्य", "Location": "स्थान", "Use current location": "वर्तमान स्थान उपयोग करें", "Search services": "सेवाएँ खोजें", "Search for a service": "सेवा खोजें", "Search for ‘plumbing’": "‘प्लंबिंग’ खोजें", "Search": "खोजें", "Notifications": "सूचनाएँ", "Sign In": "साइन इन", "Sign in": "साइन इन", "Log out": "लॉग आउट",
            "Verified professionals. Clear prices. Local expertise.": "सत्यापित पेशेवर। स्पष्ट कीमतें। स्थानीय विशेषज्ञता।", "Trusted local professionals, just a booking away.": "विश्वसनीय स्थानीय पेशेवर, बस एक बुकिंग दूर।", "Find verified professionals for cleaning, plumbing, electrical repairs and more — all in one place.": "सफाई, प्लंबिंग, बिजली मरम्मत और अन्य सेवाओं के सत्यापित पेशेवर एक ही स्थान पर पाएँ।", "Verified professionals": "सत्यापित पेशेवर", "Transparent pricing": "पारदर्शी कीमत", "Secure booking": "सुरक्षित बुकिंग", "Local support": "स्थानीय सहायता",
            "Plumbing": "प्लंबिंग", "Electrical": "बिजली", "Cleaning": "सफाई", "Vehicle Repair": "वाहन मरम्मत", "Appliance Repair": "उपकरण मरम्मत", "Beauty Services": "सौंदर्य सेवाएँ", "Moving Services": "स्थानांतरण सेवाएँ", "Emergency Services": "आपातकालीन सेवाएँ", "More Services": "और सेवाएँ", "Recommended professionals": "सुझाए गए पेशेवर", "Top-rated experts near you": "आपके पास सर्वोच्च रेटिंग वाले विशेषज्ञ", "Explore services": "सेवाएँ देखें", "Popular categories": "लोकप्रिय श्रेणियाँ", "View all services": "सभी सेवाएँ", "Complete catalogue": "पूरी सूची", "All services": "सभी सेवाएँ", "Choose a category to see its services, prices and available professionals.": "सेवाएँ, कीमतें और उपलब्ध पेशेवर देखने के लिए श्रेणी चुनें।",
            "Service category": "सेवा श्रेणी", "Choose what you need": "अपनी जरूरत चुनें", "Available services": "उपलब्ध सेवाएँ", "Available near you": "आपके पास उपलब्ध", "Service professionals": "सेवा पेशेवर", "View professionals and book this service": "पेशेवर देखें और सेवा बुक करें", "View details": "विवरण देखें", "Book": "बुक करें", "About this professional": "इस पेशेवर के बारे में", "Services & prices": "सेवाएँ और कीमतें", "Included with every booking": "हर बुकिंग में शामिल", "Reviews": "समीक्षाएँ", "Book this professional": "इस पेशेवर को बुक करें", "Starting from": "शुरुआती कीमत",
            "Start your booking": "बुकिंग शुरू करें", "Choose the service you need": "अपनी सेवा चुनें", "Service": "सेवा", "Schedule": "समय", "Address": "पता", "Confirm": "पुष्टि", "Select one service": "एक सेवा चुनें", "Continue": "जारी रखें", "Back": "पीछे", "When should the professional arrive?": "पेशेवर कब आए?", "Choose an available date and arrival window.": "उपलब्ध तारीख और समय चुनें।", "Select a date": "तारीख चुनें", "Select a time": "समय चुनें", "Where do you need the service?": "सेवा कहाँ चाहिए?", "Full name": "पूरा नाम", "Phone number": "फोन नंबर", "Address label": "पते का नाम", "City": "शहर", "State": "राज्य", "PIN code": "पिन कोड", "Landmark": "लैंडमार्क", "Review and confirm": "जाँचें और पुष्टि करें", "Payment method": "भुगतान विधि", "Pay after service": "सेवा के बाद भुगतान", "Save booking request": "बुकिंग अनुरोध सहेजें", "Done": "पूर्ण",
            "Trusted help, close to home": "घर के पास विश्वसनीय सहायता", "Welcome back": "वापसी पर स्वागत", "Email address": "ईमेल पता", "Password": "पासवर्ड", "Forgot password?": "पासवर्ड भूल गए?", "Enter your password": "पासवर्ड दर्ज करें", "Show": "दिखाएँ", "Hide": "छिपाएँ", "Remember me": "मुझे याद रखें", "Don’t have an account?": "खाता नहीं है?", "Create account": "खाता बनाएँ", "Join the community": "समुदाय से जुड़ें", "Create your account": "अपना खाता बनाएँ", "Already have an account?": "पहले से खाता है?", "Verification code": "सत्यापन कोड", "Send code": "कोड भेजें", "Resend code": "कोड फिर भेजें", "Confirm password": "पासवर्ड की पुष्टि", "Reset password": "पासवर्ड रीसेट", "Update password": "पासवर्ड बदलें",
            "My account": "मेरा खाता", "Overview": "अवलोकन", "My profile": "मेरी प्रोफ़ाइल", "Saved addresses": "सहेजे पते", "Active bookings": "सक्रिय बुकिंग", "Booking history": "बुकिंग इतिहास", "Favourites": "पसंदीदा", "Settings": "सेटिंग्स", "Good": "शुभ", "morning": "प्रभात", "afternoon": "दोपहर", "evening": "संध्या", "Customer": "ग्राहक", "Book a service": "सेवा बुक करें", "Upcoming": "आगामी", "Completed services": "पूरी सेवाएँ", "Total spent": "कुल खर्च", "Latest booking": "नवीनतम बुकिंग", "Quick actions": "त्वरित कार्य", "Edit profile": "प्रोफ़ाइल बदलें", "Add an address": "पता जोड़ें", "Find a professional": "पेशेवर खोजें", "Account settings": "खाता सेटिंग्स", "Profile photo": "प्रोफ़ाइल फोटो", "Date of birth": "जन्म तारीख", "Preferred language": "पसंदीदा भाषा", "Discard changes": "बदलाव रद्द", "Save profile": "प्रोफ़ाइल सहेजें", "Add address": "पता जोड़ें", "Save address": "पता सहेजें", "Cancel": "रद्द", "Past services": "पिछली सेवाएँ", "Search bookings": "बुकिंग खोजें", "All statuses": "सभी स्थितियाँ", "Completed": "पूर्ण", "Cancelled": "रद्द", "Favourite professionals": "पसंदीदा पेशेवर", "Mark all as read": "सभी को पढ़ा मानें", "Preferences and security": "प्राथमिकताएँ और सुरक्षा", "Booking updates": "बुकिंग अपडेट", "Offers and recommendations": "ऑफर और सुझाव", "Email receipts": "ईमेल रसीदें", "Appearance": "दिखावट", "Theme": "थीम", "Light": "लाइट", "Night": "नाइट", "Save settings": "सेटिंग्स सहेजें"
        }
    };

    Object.assign(translations.kn, {
        "Verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ", "Simple booking": "ಸರಳ ಬುಕಿಂಗ್", "Reliable from start to finish": "ಆರಂಭದಿಂದ ಅಂತ್ಯದವರೆಗೆ ವಿಶ್ವಾಸಾರ್ಹ", "Local help, made simple": "ಸ್ಥಳೀಯ ಸಹಾಯ ಈಗ ಸರಳ", "Secure password reset": "ಸುರಕ್ಷಿತ ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಕೆ", "Prices shown are starting estimates": "ತೋರಿಸಿದ ಬೆಲೆಗಳು ಆರಂಭಿಕ ಅಂದಾಜುಗಳು", "Available now": "ಈಗ ಲಭ್ಯ", "Available today": "ಇಂದು ಲಭ್ಯ", "Available tomorrow": "ನಾಳೆ ಲಭ್ಯ",
        "Home repair": "ಮನೆ ದುರಸ್ತಿ", "Home care": "ಮನೆ ಆರೈಕೆ", "Cooling service": "ಕೂಲಿಂಗ್ ಸೇವೆ", "Auto care": "ವಾಹನ ಆರೈಕೆ", "Two-wheeler care": "ದ್ವಿಚಕ್ರ ವಾಹನ ಆರೈಕೆ",
        "Secure & encrypted": "ಸುರಕ್ಷಿತ ಮತ್ತು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ", "Verified local professionals": "ಪರಿಶೀಲಿತ ಸ್ಥಳೀಯ ವೃತ್ತಿಪರರು", "Clear prices before booking": "ಬುಕಿಂಗ್ ಮೊದಲು ಸ್ಪಷ್ಟ ಬೆಲೆ", "Simple appointment management": "ಸರಳ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ನಿರ್ವಹಣೆ", "Get started": "ಪ್ರಾರಂಭಿಸಿ", "Step 1 of 2": "2ರಲ್ಲಿ ಹಂತ 1", "Account recovery": "ಖಾತೆ ಮರುಪಡೆಯುವಿಕೆ", "Reset your password": "ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ", "and": "ಮತ್ತು",
        "“Finding dependable help should feel effortless.”": "“ವಿಶ್ವಾಸಾರ್ಹ ಸಹಾಯ ಹುಡುಕುವುದು ಸುಲಭವಾಗಿರಬೇಕು.”", "“The plumber arrived on time, explained the repair clearly and finished without leaving a mess.”": "“ಪ್ಲಂಬರ್ ಸಮಯಕ್ಕೆ ಬಂದು, ದುರಸ್ತಿಯನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ವಿವರಿಸಿ, ಯಾವುದೇ ಅವ್ಯವಸ್ಥೆ ಬಿಡದೆ ಕೆಲಸ ಮುಗಿಸಿದರು.”", "“Booking an electrician took only a few minutes. The pricing was clear and the work felt very professional.”": "“ಎಲೆಕ್ಟ್ರಿಷಿಯನ್ ಬುಕ್ ಮಾಡಲು ಕೆಲವೇ ನಿಮಿಷಗಳು ಬೇಕಾಯಿತು. ಬೆಲೆ ಸ್ಪಷ್ಟವಾಗಿತ್ತು ಮತ್ತು ಕೆಲಸ ತುಂಬಾ ವೃತ್ತಿಪರವಾಗಿತ್ತು.”", "“I could compare ratings before choosing. The cleaning team was polite, careful and thorough.”": "“ಆಯ್ಕೆ ಮಾಡುವ ಮೊದಲು ರೇಟಿಂಗ್‌ಗಳನ್ನು ಹೋಲಿಸಬಹುದಾಯಿತು. ಸ್ವಚ್ಛತಾ ತಂಡ ವಿನಯಶೀಲವಾಗಿ, ಎಚ್ಚರಿಕೆಯಿಂದ ಮತ್ತು ಸಂಪೂರ್ಣವಾಗಿ ಕೆಲಸ ಮಾಡಿತು.”",
        "Compare trusted providers by ratings, experience, arrival time and starting price.": "ರೇಟಿಂಗ್‌ಗಳು, ಅನುಭವ, ಆಗಮನ ಸಮಯ ಮತ್ತು ಆರಂಭಿಕ ಬೆಲೆಯ ಮೂಲಕ ವಿಶ್ವಾಸಾರ್ಹ ಸೇವಾದಾರರನ್ನು ಹೋಲಿಸಿ.",
        "VERIFIED": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ", "From": "ಇಂದ", "Arrival": "ಆಗಮನ", "Jobs": "ಕೆಲಸಗಳು", "View professional": "ವೃತ್ತಿಪರರನ್ನು ನೋಡಿ",
        "Complete AC Care": "ಸಂಪೂರ್ಣ ಎಸಿ ಸೇವೆ", "Expert Plumbing": "ತಜ್ಞ ಪ್ಲಂಬಿಂಗ್", "Safe Electricals": "ಸುರಕ್ಷಿತ ವಿದ್ಯುತ್ ಸೇವೆ", "Premium Cleaning": "ಪ್ರೀಮಿಯಂ ಸ್ವಚ್ಛತೆ", "Complete Car Care": "ಸಂಪೂರ್ಣ ಕಾರು ಸೇವೆ", "Bike Service Pro": "ತಜ್ಞ ಬೈಕ್ ಸೇವೆ",
        "Home Cleaning": "ಮನೆ ಸ್ವಚ್ಛತೆ", "Leaks, taps and pipe repairs": "ಸೋರಿಕೆ, ನಳ ಮತ್ತು ಪೈಪ್ ದುರಸ್ತಿ", "Wiring, fixtures and safety checks": "ವೈರಿಂಗ್, ಫಿಕ್ಚರ್ ಮತ್ತು ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆ", "Regular and deep home cleaning": "ನಿಯಮಿತ ಮತ್ತು ಆಳವಾದ ಮನೆ ಸ್ವಚ್ಛತೆ", "Car and bike service near you": "ನಿಮ್ಮ ಹತ್ತಿರ ಕಾರು ಮತ್ತು ಬೈಕ್ ಸೇವೆ", "AC, refrigerator and washer care": "ಎಸಿ, ಫ್ರಿಜ್ ಮತ್ತು ವಾಷಿಂಗ್ ಮೆಷಿನ್ ಸೇವೆ", "Salon services in your home": "ನಿಮ್ಮ ಮನೆಯಲ್ಲೇ ಸಲೂನ್ ಸೇವೆಗಳು", "Careful packing and local moves": "ಎಚ್ಚರಿಕೆಯ ಪ್ಯಾಕಿಂಗ್ ಮತ್ತು ಸ್ಥಳೀಯ ಸ್ಥಳಾಂತರ", "Fast help when you need it": "ಅಗತ್ಯವಿದ್ದಾಗ ತ್ವರಿತ ಸಹಾಯ",
        "SIMPLE BOOKING": "ಸರಳ ಬುಕಿಂಗ್", "How it works": "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ", "Find": "ಹುಡುಕಿ", "Search for the service you need.": "ನಿಮಗೆ ಬೇಕಾದ ಸೇವೆಯನ್ನು ಹುಡುಕಿ.", "Compare": "ಹೋಲಿಸಿ", "Check ratings, prices and availability.": "ರೇಟಿಂಗ್, ಬೆಲೆ ಮತ್ತು ಲಭ್ಯತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.", "Choose a convenient date and time.": "ಅನುಕೂಲಕರ ದಿನಾಂಕ ಮತ್ತು ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.", "Relax": "ನಿಶ್ಚಿಂತವಾಗಿರಿ", "Your professional handles the job.": "ನಿಮ್ಮ ವೃತ್ತಿಪರರು ಕೆಲಸವನ್ನು ನೋಡಿಕೊಳ್ಳುತ್ತಾರೆ.", "Review": "ವಿಮರ್ಶಿಸಿ", "Share your experience with your community.": "ನಿಮ್ಮ ಅನುಭವವನ್ನು ಸಮುದಾಯದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ.",
        "RELIABLE FROM START TO FINISH": "ಆರಂಭದಿಂದ ಅಂತ್ಯದವರೆಗೆ ವಿಶ್ವಾಸಾರ್ಹ", "Why choose LocalConnect": "LocalConnect ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು", "Everything you need to book local help with confidence.": "ಸ್ಥಳೀಯ ಸಹಾಯವನ್ನು ವಿಶ್ವಾಸದಿಂದ ಬುಕ್ ಮಾಡಲು ಬೇಕಾದ ಎಲ್ಲವೂ.", "Background-checked service partners.": "ಹಿನ್ನೆಲೆ ಪರಿಶೀಲಿಸಿದ ಸೇವಾ ಪಾಲುದಾರರು.", "Clear estimates before you book.": "ಬುಕ್ ಮಾಡುವ ಮೊದಲು ಸ್ಪಷ್ಟ ಅಂದಾಜು.", "Live location tracking": "ನೇರ ಸ್ಥಳ ಟ್ರ್ಯಾಕಿಂಗ್", "Know when your professional arrives.": "ನಿಮ್ಮ ವೃತ್ತಿಪರರು ಯಾವಾಗ ಬರುತ್ತಾರೆಂದು ತಿಳಿಯಿರಿ.", "Secure payments": "ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು", "Protected, convenient transactions.": "ರಕ್ಷಿತ ಮತ್ತು ಅನುಕೂಲಕರ ವ್ಯವಹಾರಗಳು.", "Service warranty": "ಸೇವಾ ವಾರಂಟಿ", "Support if something is not right.": "ಏನಾದರೂ ಸರಿಯಿಲ್ಲದಿದ್ದರೆ ಸಹಾಯ.", "Customer support": "ಗ್ರಾಹಕ ಸಹಾಯ", "Friendly help throughout your booking.": "ನಿಮ್ಮ ಬುಕಿಂಗ್ ಉದ್ದಕ್ಕೂ ಸ್ನೇಹಪರ ಸಹಾಯ.",
        "CUSTOMER STORIES": "ಗ್ರಾಹಕರ ಅನುಭವಗಳು", "Trusted by households in Davangere": "ದಾವಣಗೆರೆಯ ಕುಟುಂಬಗಳ ವಿಶ್ವಾಸ", "Booked plumbing": "ಪ್ಲಂಬಿಂಗ್ ಬುಕ್ ಮಾಡಲಾಗಿದೆ", "Booked electrical service": "ವಿದ್ಯುತ್ ಸೇವೆ ಬುಕ್ ಮಾಡಲಾಗಿದೆ", "Booked home cleaning": "ಮನೆ ಸ್ವಚ್ಛತೆ ಬುಕ್ ಮಾಡಲಾಗಿದೆ", "LOCAL HELP, MADE SIMPLE": "ಸ್ಥಳೀಯ ಸಹಾಯ ಈಗ ಸರಳ", "Need help today?": "ಇಂದು ಸಹಾಯ ಬೇಕೇ?", "Book a trusted professional near you in just a few minutes.": "ಕೆಲವೇ ನಿಮಿಷಗಳಲ್ಲಿ ನಿಮ್ಮ ಹತ್ತಿರದ ವಿಶ್ವಾಸಾರ್ಹ ವೃತ್ತಿಪರರನ್ನು ಬುಕ್ ಮಾಡಿ.", "Find a service": "ಸೇವೆಯನ್ನು ಹುಡುಕಿ", "Partner applications coming soon": "ಪಾಲುದಾರರ ಅರ್ಜಿಗಳು ಶೀಘ್ರದಲ್ಲೇ", "Reliable local help, thoughtfully connected.": "ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ಸಹಾಯ, ಜಾಣ್ಮೆಯಿಂದ ಸಂಪರ್ಕಿಸಲಾಗಿದೆ.", "Explore": "ಅನ್ವೇಷಿಸಿ", "Services": "ಸೇವೆಗಳು", "Customer stories": "ಗ್ರಾಹಕರ ಅನುಭವಗಳು", "Account": "ಖಾತೆ", "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", "Bookings": "ಬುಕಿಂಗ್‌ಗಳು", "For professionals": "ವೃತ್ತಿಪರರಿಗಾಗಿ", "Marketplace standards": "ಮಾರುಕಟ್ಟೆ ಮಾನದಂಡಗಳು", "Built for trusted neighbourhood services.": "ವಿಶ್ವಾಸಾರ್ಹ ನೆರೆಹೊರೆ ಸೇವೆಗಳಿಗಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.",
        "Your bookings.": "ನಿಮ್ಮ ಬುಕಿಂಗ್‌ಗಳು.", "Your trusted professionals.": "ನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ವೃತ್ತಿಪರರು.", "Sign in to book local experts, manage appointments and return to professionals you trust.": "ಸ್ಥಳೀಯ ತಜ್ಞರನ್ನು ಬುಕ್ ಮಾಡಲು, ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಲು ಮತ್ತು ನಿಮ್ಮ ವಿಶ್ವಾಸದ ವೃತ್ತಿಪರರನ್ನು ಮತ್ತೆ ಸಂಪರ್ಕಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.", "HOME REPAIR": "ಮನೆ ದುರಸ್ತಿ", "Expert plumbing": "ತಜ್ಞ ಪ್ಲಂಬಿಂಗ್", "Quick help for leaks, taps, pipes, and installations.": "ಸೋರಿಕೆ, ನಳ, ಪೈಪ್ ಮತ್ತು ಅಳವಡಿಕೆಗೆ ತ್ವರಿತ ಸಹಾಯ.", "Book now": "ಈಗ ಬುಕ್ ಮಾಡಿ", "Trusted electricians": "ವಿಶ್ವಾಸಾರ್ಹ ಎಲೆಕ್ಟ್ರಿಷಿಯನ್‌ಗಳು", "HOME CARE": "ಮನೆ ಆರೈಕೆ", "Professional cleaning": "ವೃತ್ತಿಪರ ಸ್ವಚ್ಛತೆ", "COOLING SERVICE": "ಕೂಲಿಂಗ್ ಸೇವೆ", "AC repair": "ಎಸಿ ದುರಸ್ತಿ", "AUTO CARE": "ವಾಹನ ಆರೈಕೆ", "Car mechanic": "ಕಾರ್ ಮೆಕ್ಯಾನಿಕ್", "TWO-WHEELER CARE": "ದ್ವಿಚಕ್ರ ವಾಹನ ಆರೈಕೆ", "Bike mechanic": "ಬೈಕ್ ಮೆಕ್ಯಾನಿಕ್", "people already joined": "ಜನರು ಈಗಾಗಲೇ ಸೇರಿದ್ದಾರೆ", "✓ Secure & encrypted": "✓ ಸುರಕ್ಷಿತ ಮತ್ತು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ", "Manage bookings, saved professionals and service addresses in one secure place.": "ಬುಕಿಂಗ್‌ಗಳು, ಉಳಿಸಿದ ವೃತ್ತಿಪರರು ಮತ್ತು ಸೇವಾ ವಿಳಾಸಗಳನ್ನು ಒಂದೇ ಸುರಕ್ಷಿತ ಸ್ಥಳದಲ್ಲಿ ನಿರ್ವಹಿಸಿ.", "By continuing, you agree to our": "ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ", "Terms": "ನಿಯಮಗಳು", "Privacy Policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
        "Local help becomes": "ಸ್ಥಳೀಯ ಸಹಾಯ ಈಗ", "much simpler here.": "ಇಲ್ಲಿ ತುಂಬಾ ಸರಳ.", "Create your account to book verified professionals and manage every service from one place.": "ಪರಿಶೀಲಿತ ವೃತ್ತಿಪರರನ್ನು ಬುಕ್ ಮಾಡಲು ಮತ್ತು ಎಲ್ಲಾ ಸೇವೆಗಳನ್ನು ಒಂದೇ ಸ್ಥಳದಿಂದ ನಿರ್ವಹಿಸಲು ಖಾತೆ ರಚಿಸಿ.", "✓ Verified local professionals": "✓ ಪರಿಶೀಲಿತ ಸ್ಥಳೀಯ ವೃತ್ತಿಪರರು", "✓ Clear prices before booking": "✓ ಬುಕಿಂಗ್ ಮೊದಲು ಸ್ಪಷ್ಟ ಬೆಲೆ", "✓ Simple appointment management": "✓ ಸರಳ ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್ ನಿರ್ವಹಣೆ", "GET STARTED": "ಪ್ರಾರಂಭಿಸಿ", "Verify your email before creating your account.": "ಖಾತೆ ರಚಿಸುವ ಮೊದಲು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.", "STEP 1 OF 2": "2ರಲ್ಲಿ ಹಂತ 1", "Send OTP": "ಒಟಿಪಿ ಕಳುಹಿಸಿ", "Your information is protected with industry-standard security.": "ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಉದ್ಯಮ ಮಾನದಂಡದ ಭದ್ರತೆಯಿಂದ ರಕ್ಷಿಸಲಾಗಿದೆ.",
        "ACCOUNT RECOVERY": "ಖಾತೆ ಮರುಪಡೆಯುವಿಕೆ", "Get securely back": "ಸುರಕ್ಷಿತವಾಗಿ ಮತ್ತೆ", "into your account.": "ನಿಮ್ಮ ಖಾತೆಗೆ ಬನ್ನಿ.", "We will send a one-time code to your registered email address.": "ನಿಮ್ಮ ನೋಂದಾಯಿತ ಇಮೇಲ್ ವಿಳಾಸಕ್ಕೆ ಒಂದು ಬಾರಿ ಬಳಸುವ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ.", "✓ Secure password reset": "✓ ಸುರಕ್ಷಿತ ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಕೆ", "Enter the email used for your account.": "ನಿಮ್ಮ ಖಾತೆಗೆ ಬಳಸಿದ ಇಮೇಲ್ ನಮೂದಿಸಿ.", "Send reset code": "ಮರುಹೊಂದಿಕೆ ಕೋಡ್ ಕಳುಹಿಸಿ", "Remembered your password?": "ಪಾಸ್‌ವರ್ಡ್ ನೆನಪಾಯಿತೇ?",
        "← Back to services": "← ಸೇವೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ", "Complete your profile": "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ", "Your bookings, trusted professionals and account details at a glance.": "ನಿಮ್ಮ ಬುಕಿಂಗ್‌ಗಳು, ವಿಶ್ವಾಸಾರ್ಹ ವೃತ್ತಿಪರರು ಮತ್ತು ಖಾತೆ ವಿವರಗಳು ಒಂದೇ ನೋಟದಲ್ಲಿ.", "View bookings →": "ಬುಕಿಂಗ್‌ಗಳನ್ನು ನೋಡಿ →", "View history →": "ಇತಿಹಾಸ ನೋಡಿ →", "View favourites →": "ಮೆಚ್ಚಿನವುಗಳನ್ನು ನೋಡಿ →", "IN PROGRESS": "ಪ್ರಗತಿಯಲ್ಲಿದೆ", "View all": "ಎಲ್ಲವನ್ನೂ ನೋಡಿ", "No active bookings": "ಸಕ್ರಿಯ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ", "Your next confirmed service will appear here.": "ನಿಮ್ಮ ಮುಂದಿನ ದೃಢೀಕೃತ ಸೇವೆ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.", "SHORTCUTS": "ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
        "In progress": "ಪ್ರಗತಿಯಲ್ಲಿದೆ", "Shortcuts": "ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು", "Personal information": "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ", "Keep your contact details up to date.": "ನಿಮ್ಮ ಸಂಪರ್ಕ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ.", "Your initials are used until photo uploads are available.": "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಲಭ್ಯವಾಗುವವರೆಗೆ ನಿಮ್ಮ ಮೊದಲಕ್ಷರಗಳನ್ನು ಬಳಸಲಾಗುತ್ತದೆ.", "Service locations": "ಸೇವಾ ಸ್ಥಳಗಳು", "Choose where professionals should arrive.": "ವೃತ್ತಿಪರರು ಬರಬೇಕಾದ ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ.", "+ Add address": "+ ವಿಳಾಸ ಸೇರಿಸಿ", "No saved addresses": "ಉಳಿಸಿದ ವಿಳಾಸಗಳಿಲ್ಲ", "Add an address to make future bookings faster.": "ಮುಂದಿನ ಬುಕಿಂಗ್‌ಗಳನ್ನು ವೇಗಗೊಳಿಸಲು ವಿಳಾಸವನ್ನು ಸೇರಿಸಿ.", "Services in progress": "ನಡೆಯುತ್ತಿರುವ ಸೇವೆಗಳು", "Track, reschedule or cancel upcoming services.": "ಮುಂಬರುವ ಸೇವೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಮರುನಿಗದಿಪಡಿಸಿ ಅಥವಾ ರದ್ದುಮಾಡಿ.", "Book another service": "ಮತ್ತೊಂದು ಸೇವೆ ಬುಕ್ ಮಾಡಿ", "Book a trusted professional and track the service here.": "ವಿಶ್ವಾಸಾರ್ಹ ವೃತ್ತಿಪರರನ್ನು ಬುಕ್ ಮಾಡಿ ಮತ್ತು ಸೇವೆಯನ್ನು ಇಲ್ಲಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.", "Browse services": "ಸೇವೆಗಳನ್ನು ನೋಡಿ", "Review completed and cancelled bookings.": "ಪೂರ್ಣಗೊಂಡ ಮತ್ತು ರದ್ದಾದ ಬುಕಿಂಗ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.", "No matching history": "ಹೊಂದುವ ಇತಿಹಾಸವಿಲ್ಲ", "Completed and cancelled services will appear here.": "ಪೂರ್ಣಗೊಂಡ ಮತ್ತು ರದ್ದಾದ ಸೇವೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.", "Saved for later": "ನಂತರಕ್ಕಾಗಿ ಉಳಿಸಲಾಗಿದೆ", "Quickly book professionals you trust.": "ನಿಮ್ಮ ವಿಶ್ವಾಸದ ವೃತ್ತಿಪರರನ್ನು ತ್ವರಿತವಾಗಿ ಬುಕ್ ಮಾಡಿ.", "No favourite professionals": "ಮೆಚ್ಚಿನ ವೃತ್ತಿಪರರಿಲ್ಲ", "Save professionals from the home page to find them here.": "ವೃತ್ತಿಪರರನ್ನು ಇಲ್ಲಿ ಹುಡುಕಲು ಮುಖಪುಟದಿಂದ ಉಳಿಸಿ.", "Stay informed": "ಮಾಹಿತಿ ಪಡೆಯಿರಿ", "Important booking and account updates appear here.": "ಪ್ರಮುಖ ಬುಕಿಂಗ್ ಮತ್ತು ಖಾತೆ ನವೀಕರಣಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.", "You're all caught up": "ಎಲ್ಲವನ್ನೂ ನೋಡಿದ್ದೀರಿ", "Booking and account updates will appear here.": "ಬುಕಿಂಗ್ ಮತ್ತು ಖಾತೆ ನವೀಕರಣಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.", "Control notifications, appearance and account access.": "ಅಧಿಸೂಚನೆಗಳು, ಗೋಚರತೆ ಮತ್ತು ಖಾತೆ ಪ್ರವೇಶವನ್ನು ನಿಯಂತ್ರಿಸಿ.", "Status and arrival notifications": "ಸ್ಥಿತಿ ಮತ್ತು ಆಗಮನ ಅಧಿಸೂಚನೆಗಳು", "Occasional LocalConnect promotions": "ಆಗಾಗ್ಗೆ LocalConnect ಪ್ರಚಾರಗಳು", "Receive payment and booking receipts": "ಪಾವತಿ ಮತ್ತು ಬುಕಿಂಗ್ ರಸೀದಿಗಳನ್ನು ಪಡೆಯಿರಿ", "Use device setting": "ಸಾಧನದ ಸೆಟ್ಟಿಂಗ್ ಬಳಸಿ", "Default booking reminder": "ಡೀಫಾಲ್ಟ್ ಬುಕಿಂಗ್ ಜ್ಞಾಪನೆ", "30 minutes before": "30 ನಿಮಿಷ ಮೊದಲು", "1 hour before": "1 ಗಂಟೆ ಮೊದಲು", "1 day before": "1 ದಿನ ಮೊದಲು", "Account access": "ಖಾತೆ ಪ್ರವೇಶ", "Log out on this device or remove locally stored account information.": "ಈ ಸಾಧನದಿಂದ ಲಾಗ್ ಔಟ್ ಮಾಡಿ ಅಥವಾ ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಿದ ಖಾತೆ ಮಾಹಿತಿಯನ್ನು ತೆಗೆದುಹಾಕಿ.", "Delete local account data": "ಸ್ಥಳೀಯ ಖಾತೆ ಡೇಟಾ ಅಳಿಸಿ",
        "Your position": "ನಿಮ್ಮ ಸ್ಥಳ", "Live location": "ನೇರ ಸ್ಥಳ", "Search a place in Google Maps": "Google Maps ನಲ್ಲಿ ಸ್ಥಳ ಹುಡುಕಿ", "Search area, street or landmark": "ಪ್ರದೇಶ, ರಸ್ತೆ ಅಥವಾ ಗುರುತು ಸ್ಥಳ ಹುಡುಕಿ", "Address search results": "ವಿಳಾಸ ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳು", "Your live location on Google Maps": "Google Maps ನಲ್ಲಿ ನಿಮ್ಮ ನೇರ ಸ್ಥಳ", "Finding your location…": "ನಿಮ್ಮ ಸ್ಥಳ ಹುಡುಕಲಾಗುತ್ತಿದೆ…", "Please allow location access when your browser asks.": "ಬ್ರೌಸರ್ ಕೇಳಿದಾಗ ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ಅನುಮತಿಸಿ.", "Current area": "ಪ್ರಸ್ತುತ ಪ್ರದೇಶ", "Finding area name…": "ಪ್ರದೇಶದ ಹೆಸರು ಹುಡುಕಲಾಗುತ್ತಿದೆ…", "Area data © OpenStreetMap contributors": "ಪ್ರದೇಶದ ಡೇಟಾ © OpenStreetMap ಕೊಡುಗೆದಾರರು", "Waiting for location permission.": "ಸ್ಥಳ ಅನುಮತಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ.", "Latitude": "ಅಕ್ಷಾಂಶ", "Longitude": "ರೇಖಾಂಶ", "Accuracy": "ನಿಖರತೆ", "Use my current location": "ನನ್ನ ಪ್ರಸ್ತುತ ಸ್ಥಳ ಬಳಸಿ", "Open in Google Maps": "Google Maps ನಲ್ಲಿ ತೆರೆಯಿರಿ", "Location unavailable": "ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ", "Location permission was denied. Allow location access in your browser settings, then try again.": "ಸ್ಥಳ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ. ಬ್ರೌಸರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ಅನುಮತಿಸಿ, ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "Your position is unavailable. Turn on your device's location service and try again.": "ನಿಮ್ಮ ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ. ಸಾಧನದ ಸ್ಥಳ ಸೇವೆಯನ್ನು ಆನ್ ಮಾಡಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "Finding your position took too long. Check your connection and try again.": "ನಿಮ್ಮ ಸ್ಥಳ ಹುಡುಕಲು ಹೆಚ್ಚು ಸಮಯ ತೆಗೆದುಕೊಂಡಿತು. ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "We could not read your current location.": "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಓದಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.", "Showing your saved live location.": "ನಿಮ್ಮ ಉಳಿಸಿದ ನೇರ ಸ್ಥಳವನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.", "Showing your selected address.": "ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ವಿಳಾಸವನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.", "Area name unavailable": "ಪ್ರದೇಶದ ಹೆಸರು ಲಭ್ಯವಿಲ್ಲ", "Live location found": "ನೇರ ಸ್ಥಳ ಕಂಡುಬಂದಿದೆ", "Requesting your current location…": "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಕೇಳಲಾಗುತ್ತಿದೆ…", "Location needs HTTPS or localhost and a browser with location support.": "ಸ್ಥಳಕ್ಕಾಗಿ HTTPS ಅಥವಾ localhost ಮತ್ತು ಸ್ಥಳ ಬೆಂಬಲವಿರುವ ಬ್ರೌಸರ್ ಅಗತ್ಯ.", "Searching for matching addresses…": "ಹೊಂದುವ ವಿಳಾಸಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ…", "The map is showing your search. Add a city, state or postcode for a more exact marker.": "ನಕ್ಷೆ ನಿಮ್ಮ ಹುಡುಕಾಟವನ್ನು ತೋರಿಸುತ್ತಿದೆ. ಹೆಚ್ಚು ನಿಖರ ಗುರುತಿಗಾಗಿ ನಗರ, ರಾಜ್ಯ ಅಥವಾ ಪೋಸ್ಟ್‌ಕೋಡ್ ಸೇರಿಸಿ.", "Address selected. Press Done to continue.": "ವಿಳಾಸ ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ. ಮುಂದುವರಿಯಲು ಮುಗಿದಿದೆ ಒತ್ತಿರಿ.", "Selected": "ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ",
        "Plumbing service": "ಪ್ಲಂಬಿಂಗ್ ಸೇವೆ", "Vehicle repair service": "ವಾಹನ ದುರಸ್ತಿ ಸೇವೆ", "Electrical service": "ವಿದ್ಯುತ್ ಸೇವೆ", "Home cleaning service": "ಮನೆ ಸ್ವಚ್ಛತಾ ಸೇವೆ", "Appliance repair service": "ಉಪಕರಣ ದುರಸ್ತಿ ಸೇವೆ", "Beauty service": "ಸೌಂದರ್ಯ ಸೇವೆ", "Moving service": "ಸ್ಥಳಾಂತರ ಸೇವೆ", "Emergency service": "ತುರ್ತು ಸೇವೆ", "Experience": "ಅನುಭವ", "Jobs completed": "ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು", "Vehicles serviced": "ಸೇವೆ ಮಾಡಿದ ವಾಹನಗಳು", "Homes cleaned": "ಸ್ವಚ್ಛಗೊಳಿಸಿದ ಮನೆಗಳು", "Repairs completed": "ಪೂರ್ಣಗೊಂಡ ದುರಸ್ತಿಗಳು", "Appointments": "ಅಪಾಯಿಂಟ್‌ಮೆಂಟ್‌ಗಳು", "Hygiene": "ಸ್ವಚ್ಛತೆ", "Certified": "ಪ್ರಮಾಣೀಕೃತ", "Moves completed": "ಪೂರ್ಣಗೊಂಡ ಸ್ಥಳಾಂತರಗಳು", "Damage cover": "ಹಾನಿ ರಕ್ಷಣೆ", "Included": "ಒಳಗೊಂಡಿದೆ", "Response time": "ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ", "Cases handled": "ನಿರ್ವಹಿಸಿದ ಪ್ರಕರಣಗಳು", "Availability": "ಲಭ್ಯತೆ", "Customer rating": "ಗ್ರಾಹಕ ರೇಟಿಂಗ್", "Final price may vary after inspection": "ಪರಿಶೀಲನೆಯ ನಂತರ ಅಂತಿಮ ಬೆಲೆ ಬದಲಾಗಬಹುದು", "Trust & verification": "ವಿಶ್ವಾಸ ಮತ್ತು ಪರಿಶೀಲನೆ", "Verified LocalConnect profile": "ಪರಿಶೀಲಿತ LocalConnect ಪ್ರೊಫೈಲ್", "Ratings shown are based on the marketplace profile data available for this professional.": "ತೋರಿಸಿದ ರೇಟಿಂಗ್‌ಗಳು ಈ ವೃತ್ತಿಪರರ ಮಾರುಕಟ್ಟೆ ಪ್ರೊಫೈಲ್ ಡೇಟಾವನ್ನು ಆಧರಿಸಿವೆ.", "Identity and service details are reviewed before the verified badge is displayed.": "ಪರಿಶೀಲಿತ ಗುರುತು ತೋರಿಸುವ ಮೊದಲು ಗುರುತು ಮತ್ತು ಸೇವಾ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.",
        "Leaks, taps, pipes, bathroom fittings and installations": "ಸೋರಿಕೆ, ನಳ, ಪೈಪ್, ಬಾತ್‌ರೂಮ್ ಫಿಟ್ಟಿಂಗ್ ಮತ್ತು ಅಳವಡಿಕೆ", "Car and bike diagnostics, servicing and mechanical repair": "ಕಾರ್ ಮತ್ತು ಬೈಕ್ ಪರೀಕ್ಷೆ, ಸೇವೆ ಮತ್ತು ಯಾಂತ್ರಿಕ ದುರಸ್ತಿ", "Wiring, switches, lighting, fans and electrical safety checks": "ವೈರಿಂಗ್, ಸ್ವಿಚ್, ಲೈಟಿಂಗ್, ಫ್ಯಾನ್ ಮತ್ತು ವಿದ್ಯುತ್ ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆ", "Regular cleaning, deep cleaning, kitchens and bathrooms": "ನಿಯಮಿತ ಸ್ವಚ್ಛತೆ, ಆಳವಾದ ಸ್ವಚ್ಛತೆ, ಅಡುಗೆಮನೆ ಮತ್ತು ಬಾತ್‌ರೂಮ್", "AC, refrigerator, washing machine and small appliance repair": "ಎಸಿ, ಫ್ರಿಜ್, ವಾಷಿಂಗ್ ಮೆಷಿನ್ ಮತ್ತು ಸಣ್ಣ ಉಪಕರಣ ದುರಸ್ತಿ", "Hair, skincare, makeup and salon treatments at home": "ಮನೆಯಲ್ಲಿ ಕೂದಲು, ಚರ್ಮದ ಆರೈಕೆ, ಮೇಕಪ್ ಮತ್ತು ಸಲೂನ್ ಚಿಕಿತ್ಸೆ", "Packing, loading, transport and local household shifting": "ಪ್ಯಾಕಿಂಗ್, ಲೋಡಿಂಗ್, ಸಾಗಣೆ ಮತ್ತು ಸ್ಥಳೀಯ ಮನೆ ಸ್ಥಳಾಂತರ", "Urgent plumbing, electrical and roadside assistance": "ತುರ್ತು ಪ್ಲಂಬಿಂಗ್, ವಿದ್ಯುತ್ ಮತ್ತು ರಸ್ತೆಬದಿ ಸಹಾಯ",
        "A verified local plumbing team for household repairs, installations and urgent water leaks. You receive a price confirmation before work begins.": "ಮನೆ ದುರಸ್ತಿ, ಅಳವಡಿಕೆ ಮತ್ತು ತುರ್ತು ನೀರು ಸೋರಿಕೆಗೆ ಪರಿಶೀಲಿತ ಸ್ಥಳೀಯ ಪ್ಲಂಬಿಂಗ್ ತಂಡ. ಕೆಲಸ ಆರಂಭಿಸುವ ಮೊದಲು ಬೆಲೆ ದೃಢೀಕರಣ ಸಿಗುತ್ತದೆ.", "A multi-brand vehicle workshop providing routine maintenance, fault diagnosis and repair for cars and motorcycles, with approval required for replacement parts.": "ಕಾರ್ ಮತ್ತು ಮೋಟಾರ್‌ಸೈಕಲ್‌ಗಳಿಗೆ ಸಾಮಾನ್ಯ ನಿರ್ವಹಣೆ, ದೋಷ ಪತ್ತೆ ಮತ್ತು ದುರಸ್ತಿ ನೀಡುವ ಬಹು-ಬ್ರ್ಯಾಂಡ್ ಕಾರ್ಯಾಗಾರ; ಬದಲಿ ಭಾಗಗಳಿಗೆ ನಿಮ್ಮ ಅನುಮತಿ ಅಗತ್ಯ.", "A certified electrician for safe home repairs and installations. All work is checked before completion, and any extra material cost is explained in advance.": "ಸುರಕ್ಷಿತ ಮನೆ ದುರಸ್ತಿ ಮತ್ತು ಅಳವಡಿಕೆಗೆ ಪ್ರಮಾಣೀಕೃತ ಎಲೆಕ್ಟ್ರಿಷಿಯನ್. ಕೆಲಸ ಮುಗಿಸುವ ಮೊದಲು ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಹೆಚ್ಚುವರಿ ಸಾಮಗ್ರಿ ವೆಚ್ಚವನ್ನು ಮುಂಚಿತವಾಗಿ ತಿಳಿಸಲಾಗುತ್ತದೆ.", "A trained cleaning team for routine and intensive home cleaning. Choose the rooms you need and see the labour price before confirming.": "ನಿಯಮಿತ ಮತ್ತು ಆಳವಾದ ಮನೆ ಸ್ವಚ್ಛತೆಗೆ ತರಬೇತಿ ಪಡೆದ ತಂಡ. ಬೇಕಾದ ಕೊಠಡಿಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ದೃಢೀಕರಿಸುವ ಮೊದಲು ಕಾರ್ಮಿಕ ವೆಚ್ಚ ನೋಡಿ.", "A multi-appliance technician offering fault checks, servicing and repair. Spare parts are charged separately only after your approval.": "ದೋಷ ಪರಿಶೀಲನೆ, ಸೇವೆ ಮತ್ತು ದುರಸ್ತಿ ನೀಡುವ ಬಹು-ಉಪಕರಣ ತಂತ್ರಜ್ಞ. ನಿಮ್ಮ ಅನುಮತಿಯ ನಂತರ ಮಾತ್ರ ಬಿಡಿ ಭಾಗಗಳಿಗೆ ಪ್ರತ್ಯೇಕ ಶುಲ್ಕ.", "Professional salon services delivered at home with sanitized tools and single-use essentials. Select individual treatments or a complete package.": "ಸ್ವಚ್ಛಗೊಳಿಸಿದ ಸಾಧನಗಳು ಮತ್ತು ಒಮ್ಮೆ ಬಳಸುವ ಅಗತ್ಯ ವಸ್ತುಗಳೊಂದಿಗೆ ಮನೆಯಲ್ಲೇ ವೃತ್ತಿಪರ ಸಲೂನ್ ಸೇವೆ. ಪ್ರತ್ಯೇಕ ಚಿಕಿತ್ಸೆ ಅಥವಾ ಸಂಪೂರ್ಣ ಪ್ಯಾಕೇಜ್ ಆಯ್ಕೆಮಾಡಿ.", "A careful local moving crew for rooms, apartments and small offices. A survey confirms the final price based on distance and load.": "ಕೊಠಡಿ, ಅಪಾರ್ಟ್‌ಮೆಂಟ್ ಮತ್ತು ಸಣ್ಣ ಕಚೇರಿಗಳಿಗೆ ಎಚ್ಚರಿಕೆಯ ಸ್ಥಳೀಯ ಸ್ಥಳಾಂತರ ತಂಡ. ದೂರ ಮತ್ತು ಹೊರೆ ಆಧರಿಸಿ ಸಮೀಕ್ಷೆಯ ನಂತರ ಅಂತಿಮ ಬೆಲೆ ದೃಢವಾಗುತ್ತದೆ.", "Fast dispatch for urgent household faults and roadside problems. The call-out fee covers arrival and diagnosis; repair costs are confirmed on site.": "ತುರ್ತು ಮನೆ ದೋಷಗಳು ಮತ್ತು ರಸ್ತೆಬದಿ ಸಮಸ್ಯೆಗಳಿಗೆ ವೇಗದ ಸೇವೆ. ಕರೆ ಶುಲ್ಕದಲ್ಲಿ ಆಗಮನ ಮತ್ತು ಪರೀಕ್ಷೆ ಒಳಗೊಂಡಿದೆ; ದುರಸ್ತಿ ವೆಚ್ಚವನ್ನು ಸ್ಥಳದಲ್ಲೇ ದೃಢೀಕರಿಸಲಾಗುತ್ತದೆ.",
        "Verified professional and safety check": "ಪರಿಶೀಲಿತ ವೃತ್ತಿಪರ ಮತ್ತು ಸುರಕ್ಷತಾ ತಪಾಸಣೆ", "Upfront estimate before repair": "ದುರಸ್ತಿಗೆ ಮೊದಲು ಸ್ಪಷ್ಟ ಅಂದಾಜು", "Basic cleanup after service": "ಸೇವೆಯ ನಂತರ ಮೂಲ ಸ್ವಚ್ಛತೆ", "Initial diagnostic check": "ಆರಂಭಿಕ ದೋಷ ಪರಿಶೀಲನೆ", "Labour estimate before work": "ಕೆಲಸಕ್ಕೆ ಮೊದಲು ಕಾರ್ಮಿಕ ವೆಚ್ಚ ಅಂದಾಜು", "Digital service summary": "ಡಿಜಿಟಲ್ ಸೇವಾ ಸಾರಾಂಶ", "Electrical safety check": "ವಿದ್ಯುತ್ ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆ", "Upfront labour estimate": "ಮುಂಗಡ ಕಾರ್ಮಿಕ ವೆಚ್ಚ ಅಂದಾಜು", "30-day workmanship support": "30 ದಿನಗಳ ಕೆಲಸದ ಗುಣಮಟ್ಟ ಸಹಾಯ", "Cleaning equipment and standard products": "ಸ್ವಚ್ಛತಾ ಉಪಕರಣ ಮತ್ತು ಪ್ರಮಾಣಿತ ಉತ್ಪನ್ನಗಳು", "Trained, background-checked team": "ತರಬೇತಿ ಪಡೆದ, ಹಿನ್ನೆಲೆ ಪರಿಶೀಲಿತ ತಂಡ", "Post-service quality check": "ಸೇವೆಯ ನಂತರ ಗುಣಮಟ್ಟ ಪರಿಶೀಲನೆ", "Fault diagnosis": "ದೋಷ ಪತ್ತೆ", "Repair estimate before work": "ಕೆಲಸಕ್ಕೆ ಮೊದಲು ದುರಸ್ತಿ ಅಂದಾಜು", "30-day workmanship warranty": "30 ದಿನಗಳ ಕೆಲಸದ ವಾರಂಟಿ", "Sanitized tools": "ಸ್ವಚ್ಛಗೊಳಿಸಿದ ಸಾಧನಗಳು", "Single-use hygiene essentials": "ಒಮ್ಮೆ ಬಳಸುವ ಸ್ವಚ್ಛತಾ ಅಗತ್ಯ ವಸ್ತುಗಳು", "Consultation before treatment": "ಚಿಕಿತ್ಸೆಗೆ ಮೊದಲು ಸಮಾಲೋಚನೆ", "Packing materials estimate": "ಪ್ಯಾಕಿಂಗ್ ಸಾಮಗ್ರಿ ಅಂದಾಜು", "Loading and unloading crew": "ಲೋಡಿಂಗ್ ಮತ್ತು ಅನ್‌ಲೋಡಿಂಗ್ ತಂಡ", "Basic transit protection": "ಮೂಲ ಸಾಗಣೆ ರಕ್ಷಣೆ", "Priority dispatch": "ಆದ್ಯತೆಯ ರವಾನೆ", "On-site safety assessment": "ಸ್ಥಳದಲ್ಲೇ ಸುರಕ್ಷತಾ ಮೌಲ್ಯಮಾಪನ", "Price approval before additional work": "ಹೆಚ್ಚುವರಿ ಕೆಲಸಕ್ಕೆ ಮೊದಲು ಬೆಲೆ ಅನುಮೋದನೆ",
        "Continue to schedule →": "ಸಮಯ ನಿಗದಿಗೆ ಮುಂದುವರಿಸಿ →",
        "Visit & inspection": "ಭೇಟಿ ಮತ್ತು ಪರಿಶೀಲನೆ", "Tap or minor leak repair": "ನಳ ಅಥವಾ ಸಣ್ಣ ಸೋರಿಕೆ ದುರಸ್ತಿ", "Toilet repair": "ಶೌಚಾಲಯ ದುರಸ್ತಿ", "Pipe blockage removal": "ಪೈಪ್ ತಡೆ ತೆರವು", "Bathroom fitting installation": "ಬಾತ್‌ರೂಮ್ ಫಿಟ್ಟಿಂಗ್ ಅಳವಡಿಕೆ", "Vehicle inspection": "ವಾಹನ ಪರಿಶೀಲನೆ", "Bike general service": "ಬೈಕ್ ಸಾಮಾನ್ಯ ಸೇವೆ", "Car oil service": "ಕಾರ್ ಆಯಿಲ್ ಸೇವೆ", "Brake inspection & service": "ಬ್ರೇಕ್ ಪರಿಶೀಲನೆ ಮತ್ತು ಸೇವೆ", "Roadside assistance": "ರಸ್ತೆಬದಿ ಸಹಾಯ", "Visit & safety inspection": "ಭೇಟಿ ಮತ್ತು ಸುರಕ್ಷತಾ ಪರಿಶೀಲನೆ", "Switch or socket repair": "ಸ್ವಿಚ್ ಅಥವಾ ಸಾಕೆಟ್ ದುರಸ್ತಿ", "Fan installation": "ಫ್ಯಾನ್ ಅಳವಡಿಕೆ", "Light fitting installation": "ಲೈಟ್ ಫಿಟ್ಟಿಂಗ್ ಅಳವಡಿಕೆ", "Partial wiring repair": "ಭಾಗಶಃ ವೈರಿಂಗ್ ದುರಸ್ತಿ", "Bathroom cleaning": "ಬಾತ್‌ರೂಮ್ ಸ್ವಚ್ಛತೆ", "Kitchen deep cleaning": "ಅಡುಗೆಮನೆ ಆಳವಾದ ಸ್ವಚ್ಛತೆ", "1 BHK full-home cleaning": "1 BHK ಸಂಪೂರ್ಣ ಮನೆ ಸ್ವಚ್ಛತೆ", "2 BHK full-home cleaning": "2 BHK ಸಂಪೂರ್ಣ ಮನೆ ಸ್ವಚ್ಛತೆ", "Sofa cleaning": "ಸೋಫಾ ಸ್ವಚ್ಛತೆ", "Appliance inspection": "ಉಪಕರಣ ಪರಿಶೀಲನೆ", "AC general service": "ಎಸಿ ಸಾಮಾನ್ಯ ಸೇವೆ", "AC deep service": "ಎಸಿ ಆಳವಾದ ಸೇವೆ", "Washing machine repair": "ವಾಷಿಂಗ್ ಮೆಷಿನ್ ದುರಸ್ತಿ", "Refrigerator repair": "ಫ್ರಿಜ್ ದುರಸ್ತಿ", "Haircut": "ಕೂದಲು ಕತ್ತರಿಸುವಿಕೆ", "Waxing package": "ವ್ಯಾಕ್ಸಿಂಗ್ ಪ್ಯಾಕೇಜ್", "Facial cleanup": "ಫೇಶಿಯಲ್ ಕ್ಲೀನ್‌ಅಪ್", "Party makeup": "ಪಾರ್ಟಿ ಮೇಕಪ್", "Manicure & pedicure": "ಮ್ಯಾನಿಕ್ಯೂರ್ ಮತ್ತು ಪೆಡಿಕ್ಯೂರ್", "Survey & booking": "ಸಮೀಕ್ಷೆ ಮತ್ತು ಬುಕಿಂಗ್", "Single-room move": "ಒಂದು ಕೊಠಡಿ ಸ್ಥಳಾಂತರ", "1 BHK local move": "1 BHK ಸ್ಥಳೀಯ ಸ್ಥಳಾಂತರ", "2 BHK local move": "2 BHK ಸ್ಥಳೀಯ ಸ್ಥಳಾಂತರ", "Small office move": "ಸಣ್ಣ ಕಚೇರಿ ಸ್ಥಳಾಂತರ", "Emergency call-out": "ತುರ್ತು ಕರೆ ಸೇವೆ", "Urgent water leak control": "ತುರ್ತು ನೀರು ಸೋರಿಕೆ ನಿಯಂತ್ರಣ", "Electrical power fault": "ವಿದ್ಯುತ್ ದೋಷ", "Door lock assistance": "ಬಾಗಿಲು ಲಾಕ್ ಸಹಾಯ", "Roadside vehicle help": "ರಸ್ತೆಬದಿ ವಾಹನ ಸಹಾಯ"
    });

    Object.assign(translations.te, {
        "Verified": "ధృవీకరించబడింది", "Simple booking": "సులభమైన బుకింగ్", "Reliable from start to finish": "మొదటి నుంచి చివరి వరకు నమ్మకం", "Local help, made simple": "స్థానిక సహాయం ఇప్పుడు సులభం", "Secure password reset": "సురక్షిత పాస్‌వర్డ్ రీసెట్", "Prices shown are starting estimates": "చూపిన ధరలు ప్రారంభ అంచనాలు", "Available now": "ఇప్పుడు అందుబాటులో", "Available today": "ఈరోజు అందుబాటులో", "Available tomorrow": "రేపు అందుబాటులో",
        "Home repair": "ఇంటి మరమ్మతు", "Home care": "ఇంటి సంరక్షణ", "Cooling service": "కూలింగ్ సేవ", "Auto care": "వాహన సంరక్షణ", "Two-wheeler care": "ద్విచక్ర వాహన సంరక్షణ",
        "Secure & encrypted": "సురక్షితం మరియు ఎన్‌క్రిప్ట్ చేయబడింది", "Verified local professionals": "ధృవీకరించిన స్థానిక నిపుణులు", "Clear prices before booking": "బుకింగ్ ముందు స్పష్టమైన ధరలు", "Simple appointment management": "సులభమైన అపాయింట్‌మెంట్ నిర్వహణ", "Get started": "ప్రారంభించండి", "Step 1 of 2": "2లో దశ 1", "Account recovery": "ఖాతా పునరుద్ధరణ", "Reset your password": "మీ పాస్‌వర్డ్‌ను రీసెట్ చేయండి", "and": "మరియు",
        "“Finding dependable help should feel effortless.”": "“నమ్మదగిన సహాయాన్ని కనుగొనడం సులభంగా ఉండాలి.”", "“The plumber arrived on time, explained the repair clearly and finished without leaving a mess.”": "“ప్లంబర్ సమయానికి వచ్చి, మరమ్మతును స్పష్టంగా వివరించి, ఎలాంటి చెత్త లేకుండా పని పూర్తి చేశారు.”", "“Booking an electrician took only a few minutes. The pricing was clear and the work felt very professional.”": "“ఎలక్ట్రీషియన్‌ను బుక్ చేయడానికి కొన్ని నిమిషాలే పట్టింది. ధర స్పష్టంగా ఉంది, పని చాలా ప్రొఫెషనల్‌గా అనిపించింది.”", "“I could compare ratings before choosing. The cleaning team was polite, careful and thorough.”": "“ఎంచుకునే ముందు రేటింగ్‌లను పోల్చగలిగాను. క్లీనింగ్ బృందం మర్యాదగా, జాగ్రత్తగా మరియు పూర్తిగా పని చేసింది.”",
        "Compare trusted providers by ratings, experience, arrival time and starting price.": "రేటింగ్‌లు, అనుభవం, చేరుకునే సమయం మరియు ప్రారంభ ధర ఆధారంగా విశ్వసనీయ సేవాదారులను పోల్చండి.",
        "VERIFIED": "ధృవీకరించబడింది", "From": "నుండి", "Arrival": "చేరుకునే సమయం", "Jobs": "పనులు", "View professional": "నిపుణుడిని చూడండి",
        "Complete AC Care": "సంపూర్ణ ఏసీ సేవ", "Expert Plumbing": "నిపుణుల ప్లంబింగ్", "Safe Electricals": "సురక్షిత విద్యుత్ సేవ", "Premium Cleaning": "ప్రీమియం క్లీనింగ్", "Complete Car Care": "సంపూర్ణ కార్ సేవ", "Bike Service Pro": "నిపుణుల బైక్ సేవ",
        "Home Cleaning": "ఇంటి శుభ్రత", "Leaks, taps and pipe repairs": "లీకులు, ట్యాపులు మరియు పైపు మరమ్మతులు", "Wiring, fixtures and safety checks": "వైరింగ్, ఫిక్చర్లు మరియు భద్రతా తనిఖీలు", "Regular and deep home cleaning": "సాధారణ మరియు డీప్ హోమ్ క్లీనింగ్", "Car and bike service near you": "మీ సమీపంలో కార్ మరియు బైక్ సేవ", "AC, refrigerator and washer care": "ఏసీ, ఫ్రిజ్ మరియు వాషింగ్ మెషిన్ సేవ", "Salon services in your home": "మీ ఇంట్లోనే సెలూన్ సేవలు", "Careful packing and local moves": "జాగ్రత్త ప్యాకింగ్ మరియు స్థానిక తరలింపు", "Fast help when you need it": "అవసరమైనప్పుడు వేగవంతమైన సహాయం",
        "SIMPLE BOOKING": "సులభమైన బుకింగ్", "How it works": "ఇది ఎలా పనిచేస్తుంది", "Find": "వెతకండి", "Search for the service you need.": "మీకు కావలసిన సేవను వెతకండి.", "Compare": "పోల్చండి", "Check ratings, prices and availability.": "రేటింగ్‌లు, ధరలు మరియు లభ్యతను చూడండి.", "Choose a convenient date and time.": "అనుకూలమైన తేదీ మరియు సమయాన్ని ఎంచుకోండి.", "Relax": "నిశ్చింతగా ఉండండి", "Your professional handles the job.": "మీ నిపుణుడు పనిని చూసుకుంటారు.", "Review": "సమీక్షించండి", "Share your experience with your community.": "మీ అనుభవాన్ని సమాజంతో పంచుకోండి.",
        "RELIABLE FROM START TO FINISH": "మొదటి నుంచి చివరి వరకు నమ్మకం", "Why choose LocalConnect": "LocalConnect‌ను ఎందుకు ఎంచుకోవాలి", "Everything you need to book local help with confidence.": "స్థానిక సహాయాన్ని నమ్మకంగా బుక్ చేయడానికి కావలసిన అన్నీ.", "Background-checked service partners.": "నేపథ్య తనిఖీ చేసిన సేవా భాగస్వాములు.", "Clear estimates before you book.": "బుక్ చేసే ముందు స్పష్టమైన అంచనాలు.", "Live location tracking": "ప్రత్యక్ష లొకేషన్ ట్రాకింగ్", "Know when your professional arrives.": "మీ నిపుణుడు ఎప్పుడు వస్తారో తెలుసుకోండి.", "Secure payments": "సురక్షిత చెల్లింపులు", "Protected, convenient transactions.": "రక్షితమైన, సౌకర్యవంతమైన లావాదేవీలు.", "Service warranty": "సేవా వారంటీ", "Support if something is not right.": "ఏదైనా సరిగా లేకపోతే సహాయం.", "Customer support": "కస్టమర్ సహాయం", "Friendly help throughout your booking.": "మీ బుకింగ్ అంతటా స్నేహపూర్వక సహాయం.",
        "CUSTOMER STORIES": "కస్టమర్ అనుభవాలు", "Trusted by households in Davangere": "దావణగెరె కుటుంబాల విశ్వాసం", "Booked plumbing": "ప్లంబింగ్ బుక్ చేశారు", "Booked electrical service": "విద్యుత్ సేవ బుక్ చేశారు", "Booked home cleaning": "ఇంటి శుభ్రత బుక్ చేశారు", "LOCAL HELP, MADE SIMPLE": "స్థానిక సహాయం ఇప్పుడు సులభం", "Need help today?": "ఈరోజు సహాయం కావాలా?", "Book a trusted professional near you in just a few minutes.": "కొన్ని నిమిషాల్లో మీ సమీపంలోని విశ్వసనీయ నిపుణుడిని బుక్ చేయండి.", "Find a service": "సేవను వెతకండి", "Partner applications coming soon": "భాగస్వామి దరఖాస్తులు త్వరలో", "Reliable local help, thoughtfully connected.": "విశ్వసనీయ స్థానిక సహాయం, జాగ్రత్తగా అనుసంధానం.", "Explore": "అన్వేషించండి", "Services": "సేవలు", "Customer stories": "కస్టమర్ అనుభవాలు", "Account": "ఖాతా", "Dashboard": "డ్యాష్‌బోర్డ్", "Bookings": "బుకింగ్‌లు", "For professionals": "నిపుణుల కోసం", "Marketplace standards": "మార్కెట్‌ప్లేస్ ప్రమాణాలు", "Built for trusted neighbourhood services.": "విశ్వసనీయ పొరుగు సేవల కోసం రూపొందించబడింది.",
        "Your bookings.": "మీ బుకింగ్‌లు.", "Your trusted professionals.": "మీ విశ్వసనీయ నిపుణులు.", "Sign in to book local experts, manage appointments and return to professionals you trust.": "స్థానిక నిపుణులను బుక్ చేయడానికి, అపాయింట్‌మెంట్‌లను నిర్వహించడానికి మరియు మీరు నమ్మే నిపుణులను మళ్లీ సంప్రదించడానికి సైన్ ఇన్ చేయండి.", "HOME REPAIR": "ఇంటి మరమ్మతు", "Expert plumbing": "నిపుణుల ప్లంబింగ్", "Quick help for leaks, taps, pipes, and installations.": "లీకులు, ట్యాపులు, పైపులు మరియు ఇన్‌స్టాలేషన్‌లకు వేగవంతమైన సహాయం.", "Book now": "ఇప్పుడే బుక్ చేయండి", "Trusted electricians": "విశ్వసనీయ ఎలక్ట్రీషియన్లు", "HOME CARE": "ఇంటి సంరక్షణ", "Professional cleaning": "ప్రొఫెషనల్ క్లీనింగ్", "COOLING SERVICE": "కూలింగ్ సేవ", "AC repair": "ఏసీ మరమ్మతు", "AUTO CARE": "వాహన సంరక్షణ", "Car mechanic": "కార్ మెకానిక్", "TWO-WHEELER CARE": "ద్విచక్ర వాహన సంరక్షణ", "Bike mechanic": "బైక్ మెకానిక్", "people already joined": "మంది ఇప్పటికే చేరారు", "✓ Secure & encrypted": "✓ సురక్షితం మరియు ఎన్‌క్రిప్ట్ చేయబడింది", "Manage bookings, saved professionals and service addresses in one secure place.": "బుకింగ్‌లు, సేవ్ చేసిన నిపుణులు మరియు సేవా చిరునామాలను ఒకే సురక్షిత ప్రదేశంలో నిర్వహించండి.", "By continuing, you agree to our": "కొనసాగించడం ద్వారా, మీరు మా", "Terms": "నిబంధనలు", "Privacy Policy": "గోప్యతా విధానం",
        "Local help becomes": "స్థానిక సహాయం ఇప్పుడు", "much simpler here.": "ఇక్కడ ఎంతో సులభం.", "Create your account to book verified professionals and manage every service from one place.": "ధృవీకరించిన నిపుణులను బుక్ చేయడానికి మరియు ప్రతి సేవను ఒకే చోట నిర్వహించడానికి ఖాతా సృష్టించండి.", "✓ Verified local professionals": "✓ ధృవీకరించిన స్థానిక నిపుణులు", "✓ Clear prices before booking": "✓ బుకింగ్ ముందు స్పష్టమైన ధరలు", "✓ Simple appointment management": "✓ సులభమైన అపాయింట్‌మెంట్ నిర్వహణ", "GET STARTED": "ప్రారంభించండి", "Verify your email before creating your account.": "ఖాతా సృష్టించే ముందు మీ ఇమెయిల్‌ను ధృవీకరించండి.", "STEP 1 OF 2": "2లో దశ 1", "Send OTP": "ఓటీపీ పంపండి", "Your information is protected with industry-standard security.": "మీ సమాచారం పరిశ్రమ ప్రమాణాల భద్రతతో రక్షించబడింది.",
        "ACCOUNT RECOVERY": "ఖాతా పునరుద్ధరణ", "Get securely back": "సురక్షితంగా తిరిగి", "into your account.": "మీ ఖాతాలోకి రండి.", "We will send a one-time code to your registered email address.": "మీ నమోదిత ఇమెయిల్ చిరునామాకు ఒకసారి ఉపయోగించే కోడ్ పంపుతాము.", "✓ Secure password reset": "✓ సురక్షిత పాస్‌వర్డ్ రీసెట్", "Enter the email used for your account.": "మీ ఖాతాకు ఉపయోగించిన ఇమెయిల్‌ను నమోదు చేయండి.", "Send reset code": "రీసెట్ కోడ్ పంపండి", "Remembered your password?": "పాస్‌వర్డ్ గుర్తొచ్చిందా?",
        "← Back to services": "← సేవలకు తిరిగి", "Complete your profile": "మీ ప్రొఫైల్‌ను పూర్తి చేయండి", "Your bookings, trusted professionals and account details at a glance.": "మీ బుకింగ్‌లు, విశ్వసనీయ నిపుణులు మరియు ఖాతా వివరాలు ఒకే చూపులో.", "View bookings →": "బుకింగ్‌లు చూడండి →", "View history →": "చరిత్ర చూడండి →", "View favourites →": "ఇష్టమైనవి చూడండి →", "IN PROGRESS": "కొనసాగుతోంది", "View all": "అన్నీ చూడండి", "No active bookings": "యాక్టివ్ బుకింగ్‌లు లేవు", "Your next confirmed service will appear here.": "మీ తదుపరి ధృవీకరించిన సేవ ఇక్కడ కనిపిస్తుంది.", "SHORTCUTS": "షార్ట్‌కట్‌లు",
        "In progress": "కొనసాగుతోంది", "Shortcuts": "షార్ట్‌కట్‌లు", "Personal information": "వ్యక్తిగత సమాచారం", "Keep your contact details up to date.": "మీ సంప్రదింపు వివరాలను తాజాగా ఉంచండి.", "Your initials are used until photo uploads are available.": "ఫోటో అప్‌లోడ్ అందుబాటులోకి వచ్చే వరకు మీ పేరులోని మొదటి అక్షరాలు ఉపయోగించబడతాయి.", "Service locations": "సేవా ప్రదేశాలు", "Choose where professionals should arrive.": "నిపుణులు రావాల్సిన ప్రదేశాన్ని ఎంచుకోండి.", "+ Add address": "+ చిరునామా జోడించండి", "No saved addresses": "సేవ్ చేసిన చిరునామాలు లేవు", "Add an address to make future bookings faster.": "భవిష్యత్ బుకింగ్‌లను వేగంగా చేయడానికి చిరునామాను జోడించండి.", "Services in progress": "కొనసాగుతున్న సేవలు", "Track, reschedule or cancel upcoming services.": "రాబోయే సేవలను ట్రాక్ చేయండి, మళ్లీ షెడ్యూల్ చేయండి లేదా రద్దు చేయండి.", "Book another service": "మరో సేవను బుక్ చేయండి", "Book a trusted professional and track the service here.": "విశ్వసనీయ నిపుణుడిని బుక్ చేసి సేవను ఇక్కడ ట్రాక్ చేయండి.", "Browse services": "సేవలను చూడండి", "Review completed and cancelled bookings.": "పూర్తయిన మరియు రద్దయిన బుకింగ్‌లను చూడండి.", "No matching history": "సరిపోలే చరిత్ర లేదు", "Completed and cancelled services will appear here.": "పూర్తయిన మరియు రద్దయిన సేవలు ఇక్కడ కనిపిస్తాయి.", "Saved for later": "తర్వాత కోసం సేవ్ చేసినవి", "Quickly book professionals you trust.": "మీరు నమ్మే నిపుణులను త్వరగా బుక్ చేయండి.", "No favourite professionals": "ఇష్టమైన నిపుణులు లేరు", "Save professionals from the home page to find them here.": "నిపుణులను ఇక్కడ కనుగొనడానికి హోమ్ పేజీ నుంచి సేవ్ చేయండి.", "Stay informed": "సమాచారం పొందండి", "Important booking and account updates appear here.": "ముఖ్యమైన బుకింగ్ మరియు ఖాతా అప్‌డేట్‌లు ఇక్కడ కనిపిస్తాయి.", "You're all caught up": "అన్ని అప్‌డేట్‌లు చూశారు", "Booking and account updates will appear here.": "బుకింగ్ మరియు ఖాతా అప్‌డేట్‌లు ఇక్కడ కనిపిస్తాయి.", "Control notifications, appearance and account access.": "నోటిఫికేషన్‌లు, రూపం మరియు ఖాతా యాక్సెస్‌ను నియంత్రించండి.", "Status and arrival notifications": "స్థితి మరియు చేరుకునే నోటిఫికేషన్‌లు", "Occasional LocalConnect promotions": "అప్పుడప్పుడు LocalConnect ప్రమోషన్‌లు", "Receive payment and booking receipts": "చెల్లింపు మరియు బుకింగ్ రసీదులు పొందండి", "Use device setting": "పరికర సెట్టింగ్ ఉపయోగించండి", "Default booking reminder": "డిఫాల్ట్ బుకింగ్ రిమైండర్", "30 minutes before": "30 నిమిషాల ముందు", "1 hour before": "1 గంట ముందు", "1 day before": "1 రోజు ముందు", "Account access": "ఖాతా యాక్సెస్", "Log out on this device or remove locally stored account information.": "ఈ పరికరం నుంచి లాగ్ అవుట్ చేయండి లేదా స్థానికంగా సేవ్ చేసిన ఖాతా సమాచారాన్ని తొలగించండి.", "Delete local account data": "స్థానిక ఖాతా డేటాను తొలగించండి",
        "Your position": "మీ స్థానం", "Live location": "ప్రత్యక్ష స్థానం", "Search a place in Google Maps": "Google Maps‌లో ప్రదేశాన్ని వెతకండి", "Search area, street or landmark": "ప్రాంతం, వీధి లేదా గుర్తును వెతకండి", "Address search results": "చిరునామా శోధన ఫలితాలు", "Your live location on Google Maps": "Google Maps‌లో మీ ప్రత్యక్ష స్థానం", "Finding your location…": "మీ స్థానం వెతుకుతోంది…", "Please allow location access when your browser asks.": "బ్రౌజర్ అడిగినప్పుడు లొకేషన్ యాక్సెస్‌ను అనుమతించండి.", "Current area": "ప్రస్తుత ప్రాంతం", "Finding area name…": "ప్రాంతం పేరు వెతుకుతోంది…", "Area data © OpenStreetMap contributors": "ప్రాంత డేటా © OpenStreetMap సహకారులు", "Waiting for location permission.": "లొకేషన్ అనుమతి కోసం వేచి ఉంది.", "Latitude": "అక్షాంశం", "Longitude": "రేఖాంశం", "Accuracy": "ఖచ్చితత్వం", "Use my current location": "నా ప్రస్తుత స్థానం ఉపయోగించండి", "Open in Google Maps": "Google Maps‌లో తెరవండి", "Location unavailable": "స్థానం అందుబాటులో లేదు", "Location permission was denied. Allow location access in your browser settings, then try again.": "లొకేషన్ అనుమతి నిరాకరించబడింది. బ్రౌజర్ సెట్టింగ్‌లలో లొకేషన్ యాక్సెస్‌ను అనుమతించి మళ్లీ ప్రయత్నించండి.", "Your position is unavailable. Turn on your device's location service and try again.": "మీ స్థానం అందుబాటులో లేదు. పరికరం లొకేషన్ సేవను ఆన్ చేసి మళ్లీ ప్రయత్నించండి.", "Finding your position took too long. Check your connection and try again.": "మీ స్థానం కనుగొనడానికి ఎక్కువ సమయం పట్టింది. కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.", "We could not read your current location.": "మీ ప్రస్తుత స్థానాన్ని గుర్తించలేకపోయాము.", "Showing your saved live location.": "సేవ్ చేసిన మీ ప్రత్యక్ష స్థానాన్ని చూపుతోంది.", "Showing your selected address.": "మీరు ఎంచుకున్న చిరునామాను చూపుతోంది.", "Area name unavailable": "ప్రాంతం పేరు అందుబాటులో లేదు", "Live location found": "ప్రత్యక్ష స్థానం కనుగొనబడింది", "Requesting your current location…": "మీ ప్రస్తుత స్థానాన్ని అడుగుతోంది…", "Location needs HTTPS or localhost and a browser with location support.": "లొకేషన్‌కు HTTPS లేదా localhost మరియు లొకేషన్ మద్దతున్న బ్రౌజర్ అవసరం.", "Searching for matching addresses…": "సరిపోలే చిరునామాలను వెతుకుతోంది…", "The map is showing your search. Add a city, state or postcode for a more exact marker.": "మ్యాప్ మీ శోధనను చూపుతోంది. మరింత ఖచ్చితమైన గుర్తు కోసం నగరం, రాష్ట్రం లేదా పోస్టుకోడ్‌ను జోడించండి.", "Address selected. Press Done to continue.": "చిరునామా ఎంచుకోబడింది. కొనసాగడానికి పూర్తయింది నొక్కండి.", "Selected": "ఎంచుకోబడింది",
        "Plumbing service": "ప్లంబింగ్ సేవ", "Vehicle repair service": "వాహన మరమ్మతు సేవ", "Electrical service": "విద్యుత్ సేవ", "Home cleaning service": "ఇంటి శుభ్రత సేవ", "Appliance repair service": "ఉపకరణ మరమ్మతు సేవ", "Beauty service": "సౌందర్య సేవ", "Moving service": "తరలింపు సేవ", "Emergency service": "అత్యవసర సేవ", "Experience": "అనుభవం", "Jobs completed": "పూర్తయిన పనులు", "Vehicles serviced": "సేవ చేసిన వాహనాలు", "Homes cleaned": "శుభ్రం చేసిన ఇళ్లు", "Repairs completed": "పూర్తయిన మరమ్మతులు", "Appointments": "అపాయింట్‌మెంట్‌లు", "Hygiene": "పరిశుభ్రత", "Certified": "ధృవీకరించబడింది", "Moves completed": "పూర్తయిన తరలింపులు", "Damage cover": "నష్టం రక్షణ", "Included": "చేర్చబడింది", "Response time": "ప్రతిస్పందన సమయం", "Cases handled": "నిర్వహించిన కేసులు", "Availability": "లభ్యత", "Customer rating": "కస్టమర్ రేటింగ్", "Final price may vary after inspection": "తనిఖీ తర్వాత తుది ధర మారవచ్చు", "Trust & verification": "నమ్మకం మరియు ధృవీకరణ", "Verified LocalConnect profile": "ధృవీకరించిన LocalConnect ప్రొఫైల్", "Ratings shown are based on the marketplace profile data available for this professional.": "చూపిన రేటింగ్‌లు ఈ నిపుణుడి మార్కెట్‌ప్లేస్ ప్రొఫైల్ డేటాపై ఆధారపడి ఉన్నాయి.", "Identity and service details are reviewed before the verified badge is displayed.": "ధృవీకరణ గుర్తు చూపించే ముందు గుర్తింపు మరియు సేవా వివరాలు పరిశీలించబడతాయి.",
        "Leaks, taps, pipes, bathroom fittings and installations": "లీకులు, ట్యాపులు, పైపులు, బాత్రూమ్ ఫిట్టింగ్‌లు మరియు ఇన్‌స్టాలేషన్‌లు", "Car and bike diagnostics, servicing and mechanical repair": "కార్ మరియు బైక్ పరీక్ష, సర్వీసింగ్ మరియు మెకానికల్ మరమ్మతు", "Wiring, switches, lighting, fans and electrical safety checks": "వైరింగ్, స్విచ్‌లు, లైటింగ్, ఫ్యాన్‌లు మరియు విద్యుత్ భద్రతా తనిఖీలు", "Regular cleaning, deep cleaning, kitchens and bathrooms": "సాధారణ శుభ్రత, డీప్ క్లీనింగ్, వంటగదులు మరియు బాత్రూమ్‌లు", "AC, refrigerator, washing machine and small appliance repair": "ఏసీ, ఫ్రిజ్, వాషింగ్ మెషిన్ మరియు చిన్న ఉపకరణ మరమ్మతు", "Hair, skincare, makeup and salon treatments at home": "ఇంట్లో జుట్టు, చర్మ సంరక్షణ, మేకప్ మరియు సెలూన్ చికిత్సలు", "Packing, loading, transport and local household shifting": "ప్యాకింగ్, లోడింగ్, రవాణా మరియు స్థానిక ఇంటి తరలింపు", "Urgent plumbing, electrical and roadside assistance": "అత్యవసర ప్లంబింగ్, విద్యుత్ మరియు రోడ్డు పక్క సహాయం",
        "A verified local plumbing team for household repairs, installations and urgent water leaks. You receive a price confirmation before work begins.": "ఇంటి మరమ్మతులు, ఇన్‌స్టాలేషన్‌లు మరియు అత్యవసర నీటి లీకులకు ధృవీకరించిన స్థానిక ప్లంబింగ్ బృందం. పని ప్రారంభానికి ముందు ధర నిర్ధారణ అందుతుంది.", "A multi-brand vehicle workshop providing routine maintenance, fault diagnosis and repair for cars and motorcycles, with approval required for replacement parts.": "కార్లు మరియు మోటార్‌సైకిళ్లకు సాధారణ నిర్వహణ, లోప నిర్ధారణ మరియు మరమ్మతు అందించే మల్టీ-బ్రాండ్ వర్క్‌షాప్; మార్పిడి భాగాలకు మీ అనుమతి అవసరం.", "A certified electrician for safe home repairs and installations. All work is checked before completion, and any extra material cost is explained in advance.": "సురక్షిత ఇంటి మరమ్మతులు మరియు ఇన్‌స్టాలేషన్‌లకు ధృవీకరించిన ఎలక్ట్రీషియన్. పని పూర్తయ్యే ముందు తనిఖీ చేస్తారు మరియు అదనపు సామగ్రి ఖర్చును ముందే వివరిస్తారు.", "A trained cleaning team for routine and intensive home cleaning. Choose the rooms you need and see the labour price before confirming.": "సాధారణ మరియు లోతైన ఇంటి శుభ్రతకు శిక్షణ పొందిన బృందం. కావలసిన గదులను ఎంచుకుని నిర్ధారించే ముందు కార్మిక ధరను చూడండి.", "A multi-appliance technician offering fault checks, servicing and repair. Spare parts are charged separately only after your approval.": "లోప తనిఖీ, సర్వీసింగ్ మరియు మరమ్మతు అందించే బహుళ ఉపకరణ టెక్నీషియన్. మీ అనుమతి తర్వాత మాత్రమే విడిభాగాలకు వేరుగా ఛార్జ్ చేస్తారు.", "Professional salon services delivered at home with sanitized tools and single-use essentials. Select individual treatments or a complete package.": "శుభ్రపరిచిన పరికరాలు మరియు ఒక్కసారి ఉపయోగించే అవసరాలతో ఇంట్లోనే ప్రొఫెషనల్ సెలూన్ సేవలు. విడి చికిత్సలు లేదా పూర్తి ప్యాకేజ్ ఎంచుకోండి.", "A careful local moving crew for rooms, apartments and small offices. A survey confirms the final price based on distance and load.": "గదులు, అపార్ట్‌మెంట్‌లు మరియు చిన్న కార్యాలయాలకు జాగ్రత్తగల స్థానిక తరలింపు బృందం. దూరం మరియు లోడ్ ఆధారంగా సర్వే తుది ధరను నిర్ధారిస్తుంది.", "Fast dispatch for urgent household faults and roadside problems. The call-out fee covers arrival and diagnosis; repair costs are confirmed on site.": "అత్యవసర ఇంటి లోపాలు మరియు రోడ్డు పక్క సమస్యలకు వేగవంతమైన సేవ. కాల్-అవుట్ రుసుములో చేరిక మరియు నిర్ధారణ ఉంటాయి; మరమ్మతు ఖర్చు అక్కడే నిర్ధారిస్తారు.",
        "Verified professional and safety check": "ధృవీకరించిన నిపుణుడు మరియు భద్రతా తనిఖీ", "Upfront estimate before repair": "మరమ్మతుకు ముందు స్పష్టమైన అంచనా", "Basic cleanup after service": "సేవ తర్వాత ప్రాథమిక శుభ్రత", "Initial diagnostic check": "ప్రారంభ లోప తనిఖీ", "Labour estimate before work": "పని ముందు కార్మిక అంచనా", "Digital service summary": "డిజిటల్ సేవా సారాంశం", "Electrical safety check": "విద్యుత్ భద్రతా తనిఖీ", "Upfront labour estimate": "ముందస్తు కార్మిక అంచనా", "30-day workmanship support": "30 రోజుల పనితనం సహాయం", "Cleaning equipment and standard products": "శుభ్రపరిచే పరికరాలు మరియు ప్రామాణిక ఉత్పత్తులు", "Trained, background-checked team": "శిక్షణ పొందిన, నేపథ్య తనిఖీ చేసిన బృందం", "Post-service quality check": "సేవ తర్వాత నాణ్యత తనిఖీ", "Fault diagnosis": "లోప నిర్ధారణ", "Repair estimate before work": "పని ముందు మరమ్మతు అంచనా", "30-day workmanship warranty": "30 రోజుల పనితనం వారంటీ", "Sanitized tools": "శుభ్రపరిచిన పరికరాలు", "Single-use hygiene essentials": "ఒక్కసారి ఉపయోగించే పరిశుభ్రత అవసరాలు", "Consultation before treatment": "చికిత్స ముందు సంప్రదింపు", "Packing materials estimate": "ప్యాకింగ్ సామగ్రి అంచనా", "Loading and unloading crew": "లోడింగ్ మరియు అన్‌లోడింగ్ బృందం", "Basic transit protection": "ప్రాథమిక రవాణా రక్షణ", "Priority dispatch": "ప్రాధాన్య పంపిణీ", "On-site safety assessment": "స్థలంలో భద్రతా అంచనా", "Price approval before additional work": "అదనపు పనికి ముందు ధర అనుమతి",
        "Continue to schedule →": "షెడ్యూల్‌కు కొనసాగండి →",
        "Visit & inspection": "సందర్శన మరియు తనిఖీ", "Tap or minor leak repair": "ట్యాప్ లేదా చిన్న లీక్ మరమ్మతు", "Toilet repair": "టాయిలెట్ మరమ్మతు", "Pipe blockage removal": "పైపు బ్లాకేజ్ తొలగింపు", "Bathroom fitting installation": "బాత్రూమ్ ఫిట్టింగ్ ఇన్‌స్టాలేషన్", "Vehicle inspection": "వాహన తనిఖీ", "Bike general service": "బైక్ సాధారణ సేవ", "Car oil service": "కార్ ఆయిల్ సేవ", "Brake inspection & service": "బ్రేక్ తనిఖీ మరియు సేవ", "Roadside assistance": "రోడ్డు పక్క సహాయం", "Visit & safety inspection": "సందర్శన మరియు భద్రతా తనిఖీ", "Switch or socket repair": "స్విచ్ లేదా సాకెట్ మరమ్మతు", "Fan installation": "ఫ్యాన్ ఇన్‌స్టాలేషన్", "Light fitting installation": "లైట్ ఫిట్టింగ్ ఇన్‌స్టాలేషన్", "Partial wiring repair": "పాక్షిక వైరింగ్ మరమ్మతు", "Bathroom cleaning": "బాత్రూమ్ శుభ్రత", "Kitchen deep cleaning": "వంటగది డీప్ క్లీనింగ్", "1 BHK full-home cleaning": "1 BHK పూర్తి ఇంటి శుభ్రత", "2 BHK full-home cleaning": "2 BHK పూర్తి ఇంటి శుభ్రత", "Sofa cleaning": "సోఫా శుభ్రత", "Appliance inspection": "ఉపకరణ తనిఖీ", "AC general service": "ఏసీ సాధారణ సేవ", "AC deep service": "ఏసీ డీప్ సేవ", "Washing machine repair": "వాషింగ్ మెషిన్ మరమ్మతు", "Refrigerator repair": "ఫ్రిజ్ మరమ్మతు", "Haircut": "హెయిర్‌కట్", "Waxing package": "వ్యాక్సింగ్ ప్యాకేజ్", "Facial cleanup": "ఫేషియల్ క్లీనప్", "Party makeup": "పార్టీ మేకప్", "Manicure & pedicure": "మ్యానిక్యూర్ మరియు పెడిక్యూర్", "Survey & booking": "సర్వే మరియు బుకింగ్", "Single-room move": "ఒక గది తరలింపు", "1 BHK local move": "1 BHK స్థానిక తరలింపు", "2 BHK local move": "2 BHK స్థానిక తరలింపు", "Small office move": "చిన్న కార్యాలయ తరలింపు", "Emergency call-out": "అత్యవసర కాల్ సేవ", "Urgent water leak control": "అత్యవసర నీటి లీక్ నియంత్రణ", "Electrical power fault": "విద్యుత్ లోపం", "Door lock assistance": "తలుపు లాక్ సహాయం", "Roadside vehicle help": "రోడ్డు పక్క వాహన సహాయం"
    });

    Object.assign(translations.hi, {
        "Verified": "सत्यापित", "Simple booking": "सरल बुकिंग", "Reliable from start to finish": "शुरुआत से अंत तक भरोसेमंद", "Local help, made simple": "स्थानीय सहायता अब सरल", "Secure password reset": "सुरक्षित पासवर्ड रीसेट", "Prices shown are starting estimates": "दिखाई कीमतें शुरुआती अनुमान हैं", "Available now": "अभी उपलब्ध", "Available today": "आज उपलब्ध", "Available tomorrow": "कल उपलब्ध",
        "Home repair": "घर की मरम्मत", "Home care": "घर की देखभाल", "Cooling service": "कूलिंग सेवा", "Auto care": "वाहन देखभाल", "Two-wheeler care": "दोपहिया देखभाल",
        "Secure & encrypted": "सुरक्षित और एन्क्रिप्टेड", "Verified local professionals": "सत्यापित स्थानीय पेशेवर", "Clear prices before booking": "बुकिंग से पहले स्पष्ट कीमत", "Simple appointment management": "सरल अपॉइंटमेंट प्रबंधन", "Get started": "शुरू करें", "Step 1 of 2": "2 में से चरण 1", "Account recovery": "खाता पुनर्प्राप्ति", "Reset your password": "अपना पासवर्ड रीसेट करें", "and": "और",
        "“Finding dependable help should feel effortless.”": "“भरोसेमंद सहायता खोजना आसान होना चाहिए।”", "“The plumber arrived on time, explained the repair clearly and finished without leaving a mess.”": "“प्लंबर समय पर आया, मरम्मत स्पष्ट रूप से समझाई और बिना गंदगी छोड़े काम पूरा किया।”", "“Booking an electrician took only a few minutes. The pricing was clear and the work felt very professional.”": "“इलेक्ट्रीशियन बुक करने में कुछ ही मिनट लगे। कीमत स्पष्ट थी और काम बहुत पेशेवर लगा।”", "“I could compare ratings before choosing. The cleaning team was polite, careful and thorough.”": "“मैं चुनने से पहले रेटिंग की तुलना कर सकी। सफाई टीम विनम्र, सावधान और पूरी तरह पेशेवर थी।”",
        "Compare trusted providers by ratings, experience, arrival time and starting price.": "रेटिंग, अनुभव, पहुँचने के समय और शुरुआती कीमत के आधार पर भरोसेमंद सेवा प्रदाताओं की तुलना करें।",
        "VERIFIED": "सत्यापित", "From": "से", "Arrival": "पहुँचने का समय", "Jobs": "काम", "View professional": "पेशेवर देखें",
        "Complete AC Care": "संपूर्ण एसी सेवा", "Expert Plumbing": "विशेषज्ञ प्लंबिंग", "Safe Electricals": "सुरक्षित विद्युत सेवा", "Premium Cleaning": "प्रीमियम सफाई", "Complete Car Care": "संपूर्ण कार सेवा", "Bike Service Pro": "विशेषज्ञ बाइक सेवा",
        "Home Cleaning": "घर की सफाई", "Leaks, taps and pipe repairs": "लीक, नल और पाइप की मरम्मत", "Wiring, fixtures and safety checks": "वायरिंग, फिटिंग और सुरक्षा जाँच", "Regular and deep home cleaning": "नियमित और गहरी घर की सफाई", "Car and bike service near you": "आपके पास कार और बाइक सेवा", "AC, refrigerator and washer care": "एसी, फ्रिज और वॉशिंग मशीन सेवा", "Salon services in your home": "आपके घर पर सैलून सेवाएँ", "Careful packing and local moves": "सावधानी से पैकिंग और स्थानीय स्थानांतरण", "Fast help when you need it": "ज़रूरत पर तेज़ सहायता",
        "SIMPLE BOOKING": "सरल बुकिंग", "How it works": "यह कैसे काम करता है", "Find": "खोजें", "Search for the service you need.": "अपनी ज़रूरत की सेवा खोजें।", "Compare": "तुलना करें", "Check ratings, prices and availability.": "रेटिंग, कीमत और उपलब्धता देखें।", "Choose a convenient date and time.": "सुविधाजनक तारीख और समय चुनें।", "Relax": "निश्चिंत रहें", "Your professional handles the job.": "आपका पेशेवर काम संभालेगा।", "Review": "समीक्षा करें", "Share your experience with your community.": "अपना अनुभव समुदाय के साथ साझा करें।",
        "RELIABLE FROM START TO FINISH": "शुरुआत से अंत तक भरोसेमंद", "Why choose LocalConnect": "LocalConnect क्यों चुनें", "Everything you need to book local help with confidence.": "स्थानीय सहायता को विश्वास से बुक करने के लिए सब कुछ।", "Background-checked service partners.": "पृष्ठभूमि-जाँचे सेवा भागीदार।", "Clear estimates before you book.": "बुकिंग से पहले स्पष्ट अनुमान।", "Live location tracking": "लाइव लोकेशन ट्रैकिंग", "Know when your professional arrives.": "जानें आपका पेशेवर कब पहुँचेगा।", "Secure payments": "सुरक्षित भुगतान", "Protected, convenient transactions.": "सुरक्षित और सुविधाजनक लेन-देन।", "Service warranty": "सेवा वारंटी", "Support if something is not right.": "कुछ ठीक न हो तो सहायता।", "Customer support": "ग्राहक सहायता", "Friendly help throughout your booking.": "पूरी बुकिंग में मित्रवत सहायता।",
        "CUSTOMER STORIES": "ग्राहकों के अनुभव", "Trusted by households in Davangere": "दावणगेरे के परिवारों का भरोसा", "Booked plumbing": "प्लंबिंग बुक की", "Booked electrical service": "बिजली सेवा बुक की", "Booked home cleaning": "घर की सफाई बुक की", "LOCAL HELP, MADE SIMPLE": "स्थानीय सहायता अब सरल", "Need help today?": "आज सहायता चाहिए?", "Book a trusted professional near you in just a few minutes.": "कुछ ही मिनटों में अपने पास भरोसेमंद पेशेवर बुक करें।", "Find a service": "सेवा खोजें", "Partner applications coming soon": "भागीदार आवेदन जल्द शुरू होंगे", "Reliable local help, thoughtfully connected.": "भरोसेमंद स्थानीय सहायता, समझदारी से जुड़ी।", "Explore": "देखें", "Services": "सेवाएँ", "Customer stories": "ग्राहक अनुभव", "Account": "खाता", "Dashboard": "डैशबोर्ड", "Bookings": "बुकिंग", "For professionals": "पेशेवरों के लिए", "Marketplace standards": "मार्केटप्लेस मानक", "Built for trusted neighbourhood services.": "भरोसेमंद पड़ोस सेवाओं के लिए बनाया गया।",
        "Your bookings.": "आपकी बुकिंग।", "Your trusted professionals.": "आपके भरोसेमंद पेशेवर।", "Sign in to book local experts, manage appointments and return to professionals you trust.": "स्थानीय विशेषज्ञ बुक करने, अपॉइंटमेंट सँभालने और भरोसेमंद पेशेवरों से फिर जुड़ने के लिए साइन इन करें।", "HOME REPAIR": "घर की मरम्मत", "Expert plumbing": "विशेषज्ञ प्लंबिंग", "Quick help for leaks, taps, pipes, and installations.": "लीक, नल, पाइप और इंस्टॉलेशन के लिए तेज़ सहायता।", "Book now": "अभी बुक करें", "Trusted electricians": "भरोसेमंद इलेक्ट्रीशियन", "HOME CARE": "घर की देखभाल", "Professional cleaning": "पेशेवर सफाई", "COOLING SERVICE": "कूलिंग सेवा", "AC repair": "एसी मरम्मत", "AUTO CARE": "वाहन देखभाल", "Car mechanic": "कार मैकेनिक", "TWO-WHEELER CARE": "दोपहिया देखभाल", "Bike mechanic": "बाइक मैकेनिक", "people already joined": "लोग पहले ही जुड़ चुके हैं", "✓ Secure & encrypted": "✓ सुरक्षित और एन्क्रिप्टेड", "Manage bookings, saved professionals and service addresses in one secure place.": "बुकिंग, सहेजे पेशेवर और सेवा पते एक सुरक्षित जगह पर सँभालें।", "By continuing, you agree to our": "जारी रखकर, आप हमारी", "Terms": "शर्तों", "Privacy Policy": "गोपनीयता नीति",
        "Local help becomes": "स्थानीय सहायता अब", "much simpler here.": "यहाँ बहुत सरल है।", "Create your account to book verified professionals and manage every service from one place.": "सत्यापित पेशेवर बुक करने और हर सेवा एक जगह से सँभालने के लिए खाता बनाएँ।", "✓ Verified local professionals": "✓ सत्यापित स्थानीय पेशेवर", "✓ Clear prices before booking": "✓ बुकिंग से पहले स्पष्ट कीमत", "✓ Simple appointment management": "✓ सरल अपॉइंटमेंट प्रबंधन", "GET STARTED": "शुरू करें", "Verify your email before creating your account.": "खाता बनाने से पहले अपना ईमेल सत्यापित करें।", "STEP 1 OF 2": "2 में से चरण 1", "Send OTP": "ओटीपी भेजें", "Your information is protected with industry-standard security.": "आपकी जानकारी उद्योग-मानक सुरक्षा से संरक्षित है।",
        "ACCOUNT RECOVERY": "खाता पुनर्प्राप्ति", "Get securely back": "सुरक्षित रूप से वापस", "into your account.": "अपने खाते में आएँ।", "We will send a one-time code to your registered email address.": "हम आपके पंजीकृत ईमेल पर एक बार उपयोग होने वाला कोड भेजेंगे।", "✓ Secure password reset": "✓ सुरक्षित पासवर्ड रीसेट", "Enter the email used for your account.": "अपने खाते में उपयोग किया ईमेल दर्ज करें।", "Send reset code": "रीसेट कोड भेजें", "Remembered your password?": "पासवर्ड याद आ गया?",
        "← Back to services": "← सेवाओं पर वापस", "Complete your profile": "अपनी प्रोफ़ाइल पूरी करें", "Your bookings, trusted professionals and account details at a glance.": "आपकी बुकिंग, भरोसेमंद पेशेवर और खाते की जानकारी एक नज़र में।", "View bookings →": "बुकिंग देखें →", "View history →": "इतिहास देखें →", "View favourites →": "पसंदीदा देखें →", "IN PROGRESS": "प्रगति में", "View all": "सभी देखें", "No active bookings": "कोई सक्रिय बुकिंग नहीं", "Your next confirmed service will appear here.": "आपकी अगली पुष्ट सेवा यहाँ दिखाई देगी।", "SHORTCUTS": "शॉर्टकट",
        "In progress": "प्रगति में", "Shortcuts": "शॉर्टकट", "Personal information": "व्यक्तिगत जानकारी", "Keep your contact details up to date.": "अपनी संपर्क जानकारी अपडेट रखें।", "Your initials are used until photo uploads are available.": "फ़ोटो अपलोड उपलब्ध होने तक आपके नाम के शुरुआती अक्षर उपयोग होंगे।", "Service locations": "सेवा स्थान", "Choose where professionals should arrive.": "चुनें कि पेशेवर कहाँ पहुँचे।", "+ Add address": "+ पता जोड़ें", "No saved addresses": "कोई सहेजा पता नहीं", "Add an address to make future bookings faster.": "आगे की बुकिंग तेज़ बनाने के लिए पता जोड़ें।", "Services in progress": "जारी सेवाएँ", "Track, reschedule or cancel upcoming services.": "आने वाली सेवाओं को ट्रैक, पुनर्निर्धारित या रद्द करें।", "Book another service": "एक और सेवा बुक करें", "Book a trusted professional and track the service here.": "भरोसेमंद पेशेवर बुक करें और सेवा यहाँ ट्रैक करें।", "Browse services": "सेवाएँ देखें", "Review completed and cancelled bookings.": "पूरी और रद्द हुई बुकिंग देखें।", "No matching history": "कोई मिलता इतिहास नहीं", "Completed and cancelled services will appear here.": "पूरी और रद्द सेवाएँ यहाँ दिखाई देंगी।", "Saved for later": "बाद के लिए सहेजा", "Quickly book professionals you trust.": "अपने भरोसेमंद पेशेवरों को जल्दी बुक करें।", "No favourite professionals": "कोई पसंदीदा पेशेवर नहीं", "Save professionals from the home page to find them here.": "पेशेवरों को यहाँ खोजने के लिए होम पेज से सहेजें।", "Stay informed": "जानकारी पाते रहें", "Important booking and account updates appear here.": "महत्वपूर्ण बुकिंग और खाता अपडेट यहाँ दिखाई देंगे।", "You're all caught up": "आपने सभी अपडेट देख लिए", "Booking and account updates will appear here.": "बुकिंग और खाता अपडेट यहाँ दिखाई देंगे।", "Control notifications, appearance and account access.": "सूचनाएँ, दिखावट और खाता पहुँच नियंत्रित करें।", "Status and arrival notifications": "स्थिति और पहुँचने की सूचनाएँ", "Occasional LocalConnect promotions": "कभी-कभी LocalConnect प्रचार", "Receive payment and booking receipts": "भुगतान और बुकिंग रसीदें पाएँ", "Use device setting": "डिवाइस सेटिंग उपयोग करें", "Default booking reminder": "डिफ़ॉल्ट बुकिंग रिमाइंडर", "30 minutes before": "30 मिनट पहले", "1 hour before": "1 घंटा पहले", "1 day before": "1 दिन पहले", "Account access": "खाता पहुँच", "Log out on this device or remove locally stored account information.": "इस डिवाइस से लॉग आउट करें या स्थानीय रूप से सहेजी खाता जानकारी हटाएँ।", "Delete local account data": "स्थानीय खाता डेटा हटाएँ",
        "Your position": "आपका स्थान", "Live location": "लाइव लोकेशन", "Search a place in Google Maps": "Google Maps में जगह खोजें", "Search area, street or landmark": "क्षेत्र, सड़क या पहचान-चिह्न खोजें", "Address search results": "पता खोज परिणाम", "Your live location on Google Maps": "Google Maps पर आपकी लाइव लोकेशन", "Finding your location…": "आपका स्थान खोज रहे हैं…", "Please allow location access when your browser asks.": "ब्राउज़र के पूछने पर स्थान की अनुमति दें।", "Current area": "वर्तमान क्षेत्र", "Finding area name…": "क्षेत्र का नाम खोज रहे हैं…", "Area data © OpenStreetMap contributors": "क्षेत्र डेटा © OpenStreetMap योगदानकर्ता", "Waiting for location permission.": "स्थान अनुमति की प्रतीक्षा है।", "Latitude": "अक्षांश", "Longitude": "देशांतर", "Accuracy": "सटीकता", "Use my current location": "मेरा वर्तमान स्थान उपयोग करें", "Open in Google Maps": "Google Maps में खोलें", "Location unavailable": "स्थान उपलब्ध नहीं", "Location permission was denied. Allow location access in your browser settings, then try again.": "स्थान अनुमति अस्वीकार हुई। ब्राउज़र सेटिंग में स्थान पहुँच की अनुमति देकर फिर प्रयास करें।", "Your position is unavailable. Turn on your device's location service and try again.": "आपका स्थान उपलब्ध नहीं। डिवाइस की स्थान सेवा चालू कर फिर प्रयास करें।", "Finding your position took too long. Check your connection and try again.": "स्थान खोजने में बहुत समय लगा। कनेक्शन जाँचकर फिर प्रयास करें।", "We could not read your current location.": "हम आपका वर्तमान स्थान नहीं पढ़ सके।", "Showing your saved live location.": "आपकी सहेजी लाइव लोकेशन दिखाई जा रही है।", "Showing your selected address.": "आपका चुना पता दिखाई जा रहा है।", "Area name unavailable": "क्षेत्र का नाम उपलब्ध नहीं", "Live location found": "लाइव लोकेशन मिली", "Requesting your current location…": "आपका वर्तमान स्थान माँगा जा रहा है…", "Location needs HTTPS or localhost and a browser with location support.": "स्थान के लिए HTTPS या localhost और स्थान-सहायक ब्राउज़र चाहिए।", "Searching for matching addresses…": "मिलते पते खोज रहे हैं…", "The map is showing your search. Add a city, state or postcode for a more exact marker.": "नक्शा आपकी खोज दिखा रहा है। अधिक सटीक निशान के लिए शहर, राज्य या पिनकोड जोड़ें।", "Address selected. Press Done to continue.": "पता चुना गया। जारी रखने के लिए पूर्ण दबाएँ।", "Selected": "चुना गया",
        "Plumbing service": "प्लंबिंग सेवा", "Vehicle repair service": "वाहन मरम्मत सेवा", "Electrical service": "बिजली सेवा", "Home cleaning service": "घर की सफाई सेवा", "Appliance repair service": "उपकरण मरम्मत सेवा", "Beauty service": "सौंदर्य सेवा", "Moving service": "स्थानांतरण सेवा", "Emergency service": "आपातकालीन सेवा", "Experience": "अनुभव", "Jobs completed": "पूरे किए काम", "Vehicles serviced": "सर्विस किए वाहन", "Homes cleaned": "साफ किए घर", "Repairs completed": "पूरी मरम्मत", "Appointments": "अपॉइंटमेंट", "Hygiene": "स्वच्छता", "Certified": "प्रमाणित", "Moves completed": "पूरे स्थानांतरण", "Damage cover": "नुकसान सुरक्षा", "Included": "शामिल", "Response time": "प्रतिक्रिया समय", "Cases handled": "संभाले मामले", "Availability": "उपलब्धता", "Customer rating": "ग्राहक रेटिंग", "Final price may vary after inspection": "निरीक्षण के बाद अंतिम कीमत बदल सकती है", "Trust & verification": "भरोसा और सत्यापन", "Verified LocalConnect profile": "सत्यापित LocalConnect प्रोफ़ाइल", "Ratings shown are based on the marketplace profile data available for this professional.": "दिखाई रेटिंग इस पेशेवर की उपलब्ध मार्केटप्लेस प्रोफ़ाइल जानकारी पर आधारित हैं।", "Identity and service details are reviewed before the verified badge is displayed.": "सत्यापित चिन्ह दिखाने से पहले पहचान और सेवा विवरण की समीक्षा होती है।",
        "Leaks, taps, pipes, bathroom fittings and installations": "लीक, नल, पाइप, बाथरूम फिटिंग और इंस्टॉलेशन", "Car and bike diagnostics, servicing and mechanical repair": "कार और बाइक जाँच, सर्विस और यांत्रिक मरम्मत", "Wiring, switches, lighting, fans and electrical safety checks": "वायरिंग, स्विच, लाइट, पंखे और बिजली सुरक्षा जाँच", "Regular cleaning, deep cleaning, kitchens and bathrooms": "नियमित सफाई, गहरी सफाई, रसोई और बाथरूम", "AC, refrigerator, washing machine and small appliance repair": "एसी, फ्रिज, वॉशिंग मशीन और छोटे उपकरण की मरम्मत", "Hair, skincare, makeup and salon treatments at home": "घर पर बाल, त्वचा देखभाल, मेकअप और सैलून उपचार", "Packing, loading, transport and local household shifting": "पैकिंग, लोडिंग, परिवहन और स्थानीय घर स्थानांतरण", "Urgent plumbing, electrical and roadside assistance": "तत्काल प्लंबिंग, बिजली और सड़क किनारे सहायता",
        "A verified local plumbing team for household repairs, installations and urgent water leaks. You receive a price confirmation before work begins.": "घरेलू मरम्मत, इंस्टॉलेशन और तत्काल पानी लीक के लिए सत्यापित स्थानीय प्लंबिंग टीम। काम शुरू होने से पहले कीमत की पुष्टि मिलती है।", "A multi-brand vehicle workshop providing routine maintenance, fault diagnosis and repair for cars and motorcycles, with approval required for replacement parts.": "कार और मोटरसाइकिल के लिए नियमित रखरखाव, खराबी जाँच और मरम्मत देने वाली मल्टी-ब्रांड कार्यशाला; बदले जाने वाले पुर्ज़ों के लिए आपकी अनुमति आवश्यक है।", "A certified electrician for safe home repairs and installations. All work is checked before completion, and any extra material cost is explained in advance.": "सुरक्षित घरेलू मरम्मत और इंस्टॉलेशन के लिए प्रमाणित इलेक्ट्रीशियन। पूरा होने से पहले काम जाँचा जाता है और अतिरिक्त सामग्री की कीमत पहले बताई जाती है।", "A trained cleaning team for routine and intensive home cleaning. Choose the rooms you need and see the labour price before confirming.": "नियमित और गहरी घर की सफाई के लिए प्रशिक्षित टीम। कमरे चुनें और पुष्टि से पहले श्रम कीमत देखें।", "A multi-appliance technician offering fault checks, servicing and repair. Spare parts are charged separately only after your approval.": "खराबी जाँच, सर्विस और मरम्मत देने वाला बहु-उपकरण तकनीशियन। आपकी मंज़ूरी के बाद ही पुर्ज़ों का अलग शुल्क लगता है।", "Professional salon services delivered at home with sanitized tools and single-use essentials. Select individual treatments or a complete package.": "साफ किए औज़ार और एक बार उपयोग होने वाली सामग्री के साथ घर पर पेशेवर सैलून सेवा। अलग उपचार या पूरा पैकेज चुनें।", "A careful local moving crew for rooms, apartments and small offices. A survey confirms the final price based on distance and load.": "कमरे, अपार्टमेंट और छोटे कार्यालय के लिए सावधान स्थानीय स्थानांतरण दल। दूरी और भार के आधार पर सर्वे अंतिम कीमत तय करता है।", "Fast dispatch for urgent household faults and roadside problems. The call-out fee covers arrival and diagnosis; repair costs are confirmed on site.": "तत्काल घरेलू खराबी और सड़क किनारे समस्या के लिए तेज़ सेवा। कॉल शुल्क में पहुँचना और जाँच शामिल है; मरम्मत लागत मौके पर तय होती है।",
        "Verified professional and safety check": "सत्यापित पेशेवर और सुरक्षा जाँच", "Upfront estimate before repair": "मरम्मत से पहले स्पष्ट अनुमान", "Basic cleanup after service": "सेवा के बाद सामान्य सफाई", "Initial diagnostic check": "प्रारंभिक खराबी जाँच", "Labour estimate before work": "काम से पहले श्रम अनुमान", "Digital service summary": "डिजिटल सेवा सारांश", "Electrical safety check": "बिजली सुरक्षा जाँच", "Upfront labour estimate": "पहले से श्रम अनुमान", "30-day workmanship support": "30 दिन की काम सहायता", "Cleaning equipment and standard products": "सफाई उपकरण और मानक उत्पाद", "Trained, background-checked team": "प्रशिक्षित, पृष्ठभूमि-जाँची टीम", "Post-service quality check": "सेवा के बाद गुणवत्ता जाँच", "Fault diagnosis": "खराबी जाँच", "Repair estimate before work": "काम से पहले मरम्मत अनुमान", "30-day workmanship warranty": "30 दिन की काम वारंटी", "Sanitized tools": "साफ किए औज़ार", "Single-use hygiene essentials": "एक बार उपयोग वाली स्वच्छता सामग्री", "Consultation before treatment": "उपचार से पहले परामर्श", "Packing materials estimate": "पैकिंग सामग्री अनुमान", "Loading and unloading crew": "लोडिंग और अनलोडिंग दल", "Basic transit protection": "बुनियादी परिवहन सुरक्षा", "Priority dispatch": "प्राथमिकता प्रेषण", "On-site safety assessment": "मौके पर सुरक्षा आकलन", "Price approval before additional work": "अतिरिक्त काम से पहले कीमत मंज़ूरी",
        "Continue to schedule →": "समय चुनने के लिए जारी रखें →",
        "Visit & inspection": "विज़िट और निरीक्षण", "Tap or minor leak repair": "नल या छोटे लीक की मरम्मत", "Toilet repair": "टॉयलेट मरम्मत", "Pipe blockage removal": "पाइप रुकावट हटाना", "Bathroom fitting installation": "बाथरूम फिटिंग इंस्टॉलेशन", "Vehicle inspection": "वाहन निरीक्षण", "Bike general service": "बाइक सामान्य सेवा", "Car oil service": "कार ऑयल सेवा", "Brake inspection & service": "ब्रेक निरीक्षण और सेवा", "Roadside assistance": "सड़क किनारे सहायता", "Visit & safety inspection": "विज़िट और सुरक्षा निरीक्षण", "Switch or socket repair": "स्विच या सॉकेट मरम्मत", "Fan installation": "पंखा इंस्टॉलेशन", "Light fitting installation": "लाइट फिटिंग इंस्टॉलेशन", "Partial wiring repair": "आंशिक वायरिंग मरम्मत", "Bathroom cleaning": "बाथरूम सफाई", "Kitchen deep cleaning": "रसोई की गहरी सफाई", "1 BHK full-home cleaning": "1 BHK पूरे घर की सफाई", "2 BHK full-home cleaning": "2 BHK पूरे घर की सफाई", "Sofa cleaning": "सोफ़ा सफाई", "Appliance inspection": "उपकरण निरीक्षण", "AC general service": "एसी सामान्य सेवा", "AC deep service": "एसी डीप सेवा", "Washing machine repair": "वॉशिंग मशीन मरम्मत", "Refrigerator repair": "फ्रिज मरम्मत", "Haircut": "हेयरकट", "Waxing package": "वैक्सिंग पैकेज", "Facial cleanup": "फेशियल क्लीनअप", "Party makeup": "पार्टी मेकअप", "Manicure & pedicure": "मैनीक्योर और पेडीक्योर", "Survey & booking": "सर्वे और बुकिंग", "Single-room move": "एक कमरे का स्थानांतरण", "1 BHK local move": "1 BHK स्थानीय स्थानांतरण", "2 BHK local move": "2 BHK स्थानीय स्थानांतरण", "Small office move": "छोटे कार्यालय का स्थानांतरण", "Emergency call-out": "आपातकालीन कॉल सेवा", "Urgent water leak control": "तत्काल पानी लीक नियंत्रण", "Electrical power fault": "बिजली की खराबी", "Door lock assistance": "दरवाज़ा लॉक सहायता", "Roadside vehicle help": "सड़क किनारे वाहन सहायता"
    });

    const templateTerms = {
        kn: { professionals: "ವೃತ್ತಿಪರರು", reviews: "ವಿಮರ್ಶೆಗಳು", minutes: "ನಿಮಿಷ", years: "ವರ್ಷಗಳು", days: "ದಿನಗಳು", away: "ದೂರ" },
        te: { professionals: "నిపుణులు", reviews: "సమీక్షలు", minutes: "నిమి", years: "సంవత్సరాలు", days: "రోజులు", away: "దూరంలో" },
        hi: { professionals: "पेशेवर", reviews: "समीक्षाएँ", minutes: "मिनट", years: "वर्ष", days: "दिन", away: "दूर" }
    };

    const originalText = new WeakMap();
    const originalAttributes = new WeakMap();
    let currentLanguage = localStorage.getItem(STORAGE_KEY) || "en";
    if (!languages[currentLanguage]) currentLanguage = "en";
    let observer;

    function t(value, language = currentLanguage) {
        if (language === "en") return value;
        const direct = translations[language]?.[value];
        if (direct) return direct;
        const terms = templateTerms[language];
        if (value.includes(" · ")) return value.split(" · ").map(part => t(part, language)).join(" · ");
        let match = value.match(/^(.+) professionals$/i);
        if (match) return `${t(match[1], language)} ${terms.professionals}`;
        match = value.match(/^(\d+) reviews$/i);
        if (match) return `${match[1]} ${terms.reviews}`;
        match = value.match(/^(★\s*[\d.]+\s*\()(\d+) reviews(\))$/i);
        if (match) return `${match[1]}${match[2]} ${terms.reviews}${match[3]}`;
        match = value.match(/^(\d+) min$/i);
        if (match) return `${match[1]} ${terms.minutes}`;
        match = value.match(/^(\d+(?:\.\d+)?) km away$/i);
        if (match) return `${match[1]} km ${terms.away}`;
        match = value.match(/^(\d+\+?) years$/i);
        if (match) return `${match[1]} ${terms.years}`;
        match = value.match(/^(\d+) days$/i);
        if (match) return `${match[1]} ${terms.days}`;
        match = value.match(/^([\d–-]+) min$/i);
        if (match) return `${match[1]} ${terms.minutes}`;
        return value;
    }

    function translateTextNode(node, resetOriginal = false) {
        if (!node.nodeValue?.trim()) return;
        const parent = node.parentElement;
        if (!parent || parent.closest("script, style, [data-i18n-ignore]")) return;
        if (resetOriginal || !originalText.has(node)) originalText.set(node, node.nodeValue);
        const source = originalText.get(node);
        const trimmed = source.trim();
        const translated = t(trimmed);
        const leading = source.match(/^\s*/)?.[0] || "";
        const trailing = source.match(/\s*$/)?.[0] || "";
        node.nodeValue = `${leading}${translated}${trailing}`;
    }

    function translateElementAttributes(element) {
        if (element.closest("[data-i18n-ignore]")) return;
        const attributes = ["placeholder", "aria-label", "title"];
        let originals = originalAttributes.get(element);
        if (!originals) {
            originals = {};
            attributes.forEach(name => {
                if (element.hasAttribute(name)) originals[name] = element.getAttribute(name);
            });
            originalAttributes.set(element, originals);
        }
        Object.entries(originals).forEach(([name, value]) => element.setAttribute(name, t(value)));
    }

    function applyTranslations(root = document) {
        observer?.disconnect();
        const elementRoot = root.nodeType === Node.ELEMENT_NODE ? root : document.documentElement;
        if (elementRoot.matches?.("[placeholder], [aria-label], [title]")) translateElementAttributes(elementRoot);
        elementRoot.querySelectorAll?.("[placeholder], [aria-label], [title]").forEach(translateElementAttributes);
        const walker = document.createTreeWalker(elementRoot, NodeFilter.SHOW_TEXT);
        let node;
        while ((node = walker.nextNode())) translateTextNode(node);
        document.documentElement.lang = currentLanguage;
        document.documentElement.dataset.language = currentLanguage;
        document.querySelectorAll("[data-language-picker]").forEach(picker => {
            const triggerLabel = picker.querySelector("[data-language-current]");
            if (triggerLabel) triggerLabel.textContent = languages[currentLanguage].label;
            picker.querySelectorAll("[data-language-option]").forEach(option => {
                const selected = option.dataset.languageOption === currentLanguage;
                option.classList.toggle("is-selected", selected);
                option.setAttribute("aria-selected", String(selected));
            });
        });
        observe();
    }

    function observe() {
        if (!observer) {
            observer = new MutationObserver(records => {
                observer.disconnect();
                records.forEach(record => {
                    if (record.type === "characterData") translateTextNode(record.target, true);
                    record.addedNodes.forEach(node => {
                        if (node.nodeType === Node.TEXT_NODE) translateTextNode(node, true);
                        else if (node.nodeType === Node.ELEMENT_NODE) applyTranslations(node);
                    });
                });
                observe();
            });
        }
        observer.observe(document.body || document.documentElement, { childList: true, subtree: true, characterData: true });
    }

    function setLanguage(language, { persist = true } = {}) {
        if (!languages[language]) return;
        currentLanguage = language;
        if (persist) localStorage.setItem(STORAGE_KEY, language);
        applyTranslations();
        window.dispatchEvent(new CustomEvent("localconnect:languagechange", {
            detail: { language, locale: languages[language].locale }
        }));
    }

    let pickerSequence = 0;

    function closePicker(wrapper, { restoreFocus = false } = {}) {
        const trigger = wrapper.querySelector(".language-trigger");
        const menu = wrapper.querySelector(".language-menu");
        if (!trigger || !menu || menu.hidden) return;
        menu.hidden = true;
        trigger.setAttribute("aria-expanded", "false");
        wrapper.classList.remove("is-open");
        if (restoreFocus) trigger.focus();
    }

    function closeOtherPickers(activePicker) {
        document.querySelectorAll("[data-language-picker]").forEach(picker => {
            if (picker !== activePicker) closePicker(picker);
        });
    }

    function openPicker(wrapper, focusDirection = 0) {
        const trigger = wrapper.querySelector(".language-trigger");
        const menu = wrapper.querySelector(".language-menu");
        closeOtherPickers(wrapper);
        menu.hidden = false;
        trigger.setAttribute("aria-expanded", "true");
        wrapper.classList.add("is-open");
        const options = [...menu.querySelectorAll("[data-language-option]")];
        const selectedIndex = Math.max(0, options.findIndex(option => option.dataset.languageOption === currentLanguage));
        const focusIndex = focusDirection < 0 ? options.length - 1 : selectedIndex;
        options[focusIndex]?.focus();
    }

    function createPicker(className) {
        pickerSequence += 1;
        const menuId = `language-menu-${pickerSequence}`;
        const wrapper = document.createElement("div");
        wrapper.className = `language-picker ${className}`;
        wrapper.dataset.languagePicker = "true";
        wrapper.dataset.i18nIgnore = "true";
        const trigger = document.createElement("button");
        trigger.type = "button";
        trigger.className = "language-trigger";
        trigger.setAttribute("aria-label", "Choose language");
        trigger.setAttribute("aria-haspopup", "listbox");
        trigger.setAttribute("aria-expanded", "false");
        trigger.setAttribute("aria-controls", menuId);
        const icon = document.createElement("img");
        icon.src = "/assets/icons/lucide/languages.svg";
        icon.alt = "";
        icon.setAttribute("aria-hidden", "true");
        const current = document.createElement("span");
        current.dataset.languageCurrent = "true";
        current.textContent = languages[currentLanguage].label;
        const chevron = document.createElement("img");
        chevron.className = "language-chevron";
        chevron.src = "/assets/icons/lucide/chevron-down.svg";
        chevron.alt = "";
        chevron.setAttribute("aria-hidden", "true");
        const menu = document.createElement("div");
        menu.id = menuId;
        menu.className = "language-menu";
        menu.setAttribute("role", "listbox");
        menu.setAttribute("aria-label", "Choose language");
        menu.hidden = true;
        Object.entries(languages).forEach(([code, data]) => {
            const option = document.createElement("button");
            option.type = "button";
            option.className = "language-option";
            option.dataset.languageOption = code;
            option.setAttribute("role", "option");
            option.setAttribute("aria-selected", String(code === currentLanguage));
            option.classList.toggle("is-selected", code === currentLanguage);
            const label = document.createElement("span");
            label.textContent = data.label;
            const check = document.createElement("span");
            check.className = "language-check";
            check.textContent = "✓";
            check.setAttribute("aria-hidden", "true");
            option.append(label, check);
            option.addEventListener("click", () => {
                setLanguage(code);
                closePicker(wrapper, { restoreFocus: true });
            });
            option.addEventListener("keydown", event => {
                const options = [...menu.querySelectorAll("[data-language-option]")];
                const index = options.indexOf(option);
                let nextIndex = null;
                if (event.key === "ArrowDown") nextIndex = (index + 1) % options.length;
                if (event.key === "ArrowUp") nextIndex = (index - 1 + options.length) % options.length;
                if (event.key === "Home") nextIndex = 0;
                if (event.key === "End") nextIndex = options.length - 1;
                if (nextIndex !== null) {
                    event.preventDefault();
                    options[nextIndex].focus();
                } else if (event.key === "Escape" || event.key === "Tab") {
                    closePicker(wrapper, { restoreFocus: event.key === "Escape" });
                }
            });
            menu.append(option);
        });
        trigger.append(icon, current, chevron);
        trigger.addEventListener("click", () => {
            if (menu.hidden) openPicker(wrapper);
            else closePicker(wrapper);
        });
        trigger.addEventListener("keydown", event => {
            if (!["ArrowDown", "ArrowUp"].includes(event.key)) return;
            event.preventDefault();
            openPicker(wrapper, event.key === "ArrowUp" ? -1 : 1);
        });
        wrapper.append(trigger, menu);
        return wrapper;
    }

    function mountPickers() {
        if (document.querySelector("[data-language-picker]")) return;
        const homeActions = document.querySelector(".header-actions");
        const authPanel = document.querySelector(".form-panel");
        const accountHeader = document.querySelector(".account-header .header-inner");
        if (homeActions) homeActions.prepend(createPicker("site-language-picker"));
        else if (authPanel) authPanel.prepend(createPicker("auth-language-picker"));
        else if (accountHeader) {
            const picker = createPicker("account-language-picker");
            accountHeader.querySelector(".back-home")?.before(picker);
        }
        applyTranslations();
    }

    document.addEventListener("click", event => {
        document.querySelectorAll("[data-language-picker]").forEach(picker => {
            if (!picker.contains(event.target)) closePicker(picker);
        });
    });

    window.LocalConnectI18n = {
        applyTranslations,
        getLanguage: () => currentLanguage,
        getLocale: () => languages[currentLanguage].locale,
        languages,
        setLanguage,
        t
    };

    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", mountPickers, { once: true });
    else mountPickers();
})();
